"""WP-TX1 Taxonomy/Tell Registry 与版本谱系。

本包实现 TX1 工作包：
- TaxonomySnapshot / AttributeDictionaryVersion / FCAContextSnapshot
- TellCore / TellFamily / TellManifestation / ObservationView / TellRecognitionRecord
- ApplicabilityBoundary / TellHintRelation (M:N)
- HintRenderer / HintInstance
- SelectorDecision / InjectionPolicy
- Progress/Termination/Critic/CompositionContract
- TellStrategyRelease / ReleaseLineage / EvidenceForeignKeyMigration
- MathValidityRecord / SystemEfficacyRecord
- InvalidationRules

关键约束：
- SIDE_EFFECT_FREE：不写 DB、不写 Redis、不写 D 盘、不调用 live model、不启动 Solver
- TellManifestation 必须不等于 TellCore（blocker）
- TellHintRelation 必须是 M:N
- 旧 Evidence 引用必须用外键迁移，Gate 不能直接改 pointer
- MathValidity 和 SystemEfficacy 分开记录
- MechanismContract core/boundary 变化 → Coverage/Case applicability 重裁定
- Renderer/Selector/TargetSolver 版本变化 → efficacy 和 cost evidence 重测
"""

from .taxonomy_snapshot import (
    TaxonomyCoordinate,
    TaxonomyEnumeration,
    TaxonomySnapshot,
    make_taxonomy_snapshot,
    TaxonomySnapshotVerificationResult,
    verify_taxonomy_snapshot,
    AttributeDefinition,
    AttributeDictionaryVersion,
    make_attribute_dictionary_version,
    AttributeDictionaryVerificationResult,
    verify_attribute_dictionary_version,
    FCAContextSnapshot,
    make_fca_context_snapshot,
    FCAContextVerificationResult,
    verify_fca_context_snapshot,
)
from .tell_core import (
    TellCore,
    make_tell_core,
    TellCoreVerificationResult,
    verify_tell_core,
    TellFamily,
    make_tell_family,
    TellFamilyVerificationResult,
    verify_tell_family,
    ObservationView,
    make_observation_view,
    TellManifestation,
    make_tell_manifestation,
    TellManifestationVerificationResult,
    verify_tell_manifestation,
    CandidateBranch,
    TellRecognitionRecord,
    make_tell_recognition_record,
    TellRecognitionVerificationResult,
    verify_tell_recognition_record,
)
from .boundary import (
    BoundaryGuard,
    ApplicabilityBoundary,
    make_applicability_boundary,
    ApplicabilityBoundaryVerificationResult,
    verify_applicability_boundary,
    TellHintRelation,
    make_tell_hint_relation,
    TellHintRelationVerificationResult,
    verify_tell_hint_relation,
    HintRenderer,
    make_hint_renderer,
    HintInstance,
    make_hint_instance,
    HintInstanceVerificationResult,
    verify_hint_instance,
    SelectorDecision,
    make_selector_decision,
    SelectorDecisionVerificationResult,
    verify_selector_decision,
    InjectionPolicy,
    make_injection_policy,
    InjectionPolicyVerificationResult,
    verify_injection_policy,
    TellContract,
    make_tell_contract,
    TellContractVerificationResult,
    verify_tell_contract,
)
from .release import (
    ReleaseComponentRef,
    TellStrategyRelease,
    make_tell_strategy_release,
    TellStrategyReleaseVerificationResult,
    verify_tell_strategy_release,
    ReleaseLineage,
    make_release_lineage,
    ReleaseLineageVerificationResult,
    verify_release_lineage,
    EvidenceForeignKeyMigration,
    make_evidence_foreign_key_migration,
    EvidenceMigrationVerificationResult,
    verify_evidence_foreign_key_migration,
    MathValidityRecord,
    make_math_validity_record,
    MathValidityVerificationResult,
    verify_math_validity_record,
    SolverResourceContext,
    SystemEfficacyRecord,
    make_system_efficacy_record,
    SystemEfficacyVerificationResult,
    verify_system_efficacy_record,
    InvalidationNotice,
    make_invalidation_notice,
    compute_invalidation_notice,
    InvalidationVerificationResult,
    verify_invalidation_notice,
    INVALIDATION_TRIGGERS,
)

__all__ = [
    # taxonomy snapshot
    "TaxonomyCoordinate",
    "TaxonomyEnumeration",
    "TaxonomySnapshot",
    "make_taxonomy_snapshot",
    "TaxonomySnapshotVerificationResult",
    "verify_taxonomy_snapshot",
    "AttributeDefinition",
    "AttributeDictionaryVersion",
    "make_attribute_dictionary_version",
    "AttributeDictionaryVerificationResult",
    "verify_attribute_dictionary_version",
    "FCAContextSnapshot",
    "make_fca_context_snapshot",
    "FCAContextVerificationResult",
    "verify_fca_context_snapshot",
    # tell core / family / manifestation / recognition
    "TellCore",
    "make_tell_core",
    "TellCoreVerificationResult",
    "verify_tell_core",
    "TellFamily",
    "make_tell_family",
    "TellFamilyVerificationResult",
    "verify_tell_family",
    "ObservationView",
    "make_observation_view",
    "TellManifestation",
    "make_tell_manifestation",
    "TellManifestationVerificationResult",
    "verify_tell_manifestation",
    "CandidateBranch",
    "TellRecognitionRecord",
    "make_tell_recognition_record",
    "TellRecognitionVerificationResult",
    "verify_tell_recognition_record",
    # boundary / hint relation / renderer / selector / injection / contract
    "BoundaryGuard",
    "ApplicabilityBoundary",
    "make_applicability_boundary",
    "ApplicabilityBoundaryVerificationResult",
    "verify_applicability_boundary",
    "TellHintRelation",
    "make_tell_hint_relation",
    "TellHintRelationVerificationResult",
    "verify_tell_hint_relation",
    "HintRenderer",
    "make_hint_renderer",
    "HintInstance",
    "make_hint_instance",
    "HintInstanceVerificationResult",
    "verify_hint_instance",
    "SelectorDecision",
    "make_selector_decision",
    "SelectorDecisionVerificationResult",
    "verify_selector_decision",
    "InjectionPolicy",
    "make_injection_policy",
    "InjectionPolicyVerificationResult",
    "verify_injection_policy",
    "TellContract",
    "make_tell_contract",
    "TellContractVerificationResult",
    "verify_tell_contract",
    # release / lineage / migration / validity / efficacy / invalidation
    "ReleaseComponentRef",
    "TellStrategyRelease",
    "make_tell_strategy_release",
    "TellStrategyReleaseVerificationResult",
    "verify_tell_strategy_release",
    "ReleaseLineage",
    "make_release_lineage",
    "ReleaseLineageVerificationResult",
    "verify_release_lineage",
    "EvidenceForeignKeyMigration",
    "make_evidence_foreign_key_migration",
    "EvidenceMigrationVerificationResult",
    "verify_evidence_foreign_key_migration",
    "MathValidityRecord",
    "make_math_validity_record",
    "MathValidityVerificationResult",
    "verify_math_validity_record",
    "SolverResourceContext",
    "SystemEfficacyRecord",
    "make_system_efficacy_record",
    "SystemEfficacyVerificationResult",
    "verify_system_efficacy_record",
    "InvalidationNotice",
    "make_invalidation_notice",
    "compute_invalidation_notice",
    "InvalidationVerificationResult",
    "verify_invalidation_notice",
    "INVALIDATION_TRIGGERS",
]
