"""GV0 固定错误码。

所有验证器返回结构化错误，不 TypeError 崩溃或跳过检查。
错误码是稳定枚举，下游消费者和审计者按码匹配，不按文本匹配。
"""

from __future__ import annotations

from enum import Enum


class VerificationErrorCode(str, Enum):
    """CompletionContractVerifier 和 SecurityContractVerifier 的固定错误码。"""

    # CompletionContractVerifier — owner / contract / schema / actor
    COMPLETION_CONTRACT_MISMATCH = "COMPLETION_CONTRACT_MISMATCH"
    ACTOR_NOT_AUTHORIZED = "ACTOR_NOT_AUTHORIZED"
    UNKNOWN_WORK_PACKAGE = "UNKNOWN_WORK_PACKAGE"
    SCHEMA_ID_MISMATCH = "SCHEMA_ID_MISMATCH"
    DAG_HASH_MISMATCH = "DAG_HASH_MISMATCH"
    DAG_LOAD_FAILED = "DAG_LOAD_FAILED"
    STATE_COMMAND_REJECTED = "STATE_COMMAND_REJECTED"

    # SecurityContractVerifier — 签名 / 授权链 / 额度
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    SIGNATURE_ALGORITHM_INVALID = "SIGNATURE_ALGORITHM_INVALID"
    SIGNATURE_DOMAIN_INVALID = "SIGNATURE_DOMAIN_INVALID"
    TIME_WINDOW_INVALID = "TIME_WINDOW_INVALID"
    TIME_NOT_CANONICAL_UTC = "TIME_NOT_CANONICAL_UTC"

    EEA_MODE_BINDING_INVALID = "EEA_MODE_BINDING_INVALID"
    EEA_ZERO_BUDGET = "EEA_ZERO_BUDGET"
    ACTION_REGISTRY_MISMATCH = "ACTION_REGISTRY_MISMATCH"

    PERMIT_ESCALATES_PARENT = "PERMIT_ESCALATES_PARENT"
    PERMIT_PARENT_HASH_MISMATCH = "PERMIT_PARENT_HASH_MISMATCH"
    DUPLICATE_ORDINAL = "DUPLICATE_ORDINAL"
    RESERVATION_BACKEND_INVALID = "RESERVATION_BACKEND_INVALID"

    RESERVATION_NOT_ATOMIC = "RESERVATION_NOT_ATOMIC"
    RELEASE_WITHOUT_PROOF = "RELEASE_WITHOUT_PROOF"
    UNKNOWN_START_MUST_HOLD = "UNKNOWN_START_MUST_HOLD"
    STALE_FENCE = "STALE_FENCE"
    ALLOWANCE_NOT_CONSERVED = "ALLOWANCE_NOT_CONSERVED"
    APPEND_ONLY_VIOLATION = "APPEND_ONLY_VIOLATION"

    # CompletionArtifactStore
    STORE_SYMLINK_REJECTED = "STORE_SYMLINK_REJECTED"
    STORE_BOUNDARY_ESCAPED = "STORE_BOUNDARY_ESCAPED"
    STORE_FALLBACK_REJECTED = "STORE_FALLBACK_REJECTED"
    STORE_HASH_MISMATCH = "STORE_HASH_MISMATCH"
    STORE_OVERWRITE_CONFLICT = "STORE_OVERWRITE_CONFLICT"
    STORE_VOLUME_ROOT_INVALID = "STORE_VOLUME_ROOT_INVALID"

    # WP-DB1L — 逻辑站点只读能力报告
    SITE_DATABASE_NAME_MISMATCH = "SITE_DATABASE_NAME_MISMATCH"
    SITE_DEFAULT_DATABASE_REJECTED = "SITE_DEFAULT_DATABASE_REJECTED"
    SITE_FINGERPRINT_MISMATCH = "SITE_FINGERPRINT_MISMATCH"
    SITE_CURRENT_DATABASE_MISMATCH = "SITE_CURRENT_DATABASE_MISMATCH"
    SITE_ENDPOINT_FINGERPRINT_MISMATCH = "SITE_ENDPOINT_FINGERPRINT_MISMATCH"
    SITE_PRINCIPAL_FINGERPRINT_MISMATCH = "SITE_PRINCIPAL_FINGERPRINT_MISMATCH"
    SITE_DRIVER_FINGERPRINT_MISMATCH = "SITE_DRIVER_FINGERPRINT_MISMATCH"
    SITE_SERVER_FINGERPRINT_MISMATCH = "SITE_SERVER_FINGERPRINT_MISMATCH"
    SITE_READONLY_PERMISSION_VIOLATION = "SITE_READONLY_PERMISSION_VIOLATION"
    CATALOG_MISSING = "CATALOG_MISSING"
    CATALOG_DRIFT = "CATALOG_DRIFT"
    CATALOG_COLLECTION_NOT_VERSIONED = "CATALOG_COLLECTION_NOT_VERSIONED"
    CATALOG_MATH_SYSTEM_COLLECTION_REUSE = "CATALOG_MATH_SYSTEM_COLLECTION_REUSE"
    CATALOG_EXTRA_SEVEN_COLLECTION = "CATALOG_EXTRA_SEVEN_COLLECTION"
    CATALOG_MISSING_SEVEN_COLLECTION = "CATALOG_MISSING_SEVEN_COLLECTION"
    DB1L_WRITE_DETECTED = "DB1L_WRITE_DETECTED"
    DB1L_CONNECTION_FAILURE = "DB1L_CONNECTION_FAILURE"
    DB1L_ZERO_WRITE_EVIDENCE_MISSING = "DB1L_ZERO_WRITE_EVIDENCE_MISSING"

    # WP-VLT0 Vault access chain
    VAULT_DENY_BY_DEFAULT_FALSE = "VAULT_DENY_BY_DEFAULT_FALSE"
    VAULT_RAW_PATH_DISCLOSED = "VAULT_RAW_PATH_DISCLOSED"
    VAULT_READ_RAW_OBJECT_REJECTED = "VAULT_READ_RAW_OBJECT_REJECTED"
    VAULT_CAPABILITY_HASH_MISMATCH = "VAULT_CAPABILITY_HASH_MISMATCH"
    VAULT_CAPABILITY_REVOKED = "VAULT_CAPABILITY_REVOKED"
    VAULT_CAPABILITY_EXPIRED = "VAULT_CAPABILITY_EXPIRED"
    VAULT_CAPABILITY_NOT_YET_VALID = "VAULT_CAPABILITY_NOT_YET_VALID"
    VAULT_NONCE_REPLAY = "VAULT_NONCE_REPLAY"
    VAULT_PRINCIPAL_MISMATCH = "VAULT_PRINCIPAL_MISMATCH"
    VAULT_OPERATION_MISMATCH = "VAULT_OPERATION_MISMATCH"
    VAULT_OBJECT_HASH_MISMATCH = "VAULT_OBJECT_HASH_MISMATCH"
    VAULT_VIEW_HASH_MISMATCH = "VAULT_VIEW_HASH_MISMATCH"
    VAULT_SINK_MISMATCH = "VAULT_SINK_MISMATCH"
    VAULT_REVOCATION_UNKNOWN = "VAULT_REVOCATION_UNKNOWN"
    VAULT_ACCESS_DENIED = "VAULT_ACCESS_DENIED"

    # WP-VLT0 View derivation
    VIEW_SOURCE_HASH_MISMATCH = "VIEW_SOURCE_HASH_MISMATCH"
    VIEW_RULE_HASH_MISMATCH = "VIEW_RULE_HASH_MISMATCH"
    VIEW_DERIVED_HASH_MISMATCH = "VIEW_DERIVED_HASH_MISMATCH"
    VIEW_SINK_RECEIPT_MISSING = "VIEW_SINK_RECEIPT_MISSING"
    VIEW_RAW_LOCATOR_EXPOSED = "VIEW_RAW_LOCATOR_EXPOSED"
    VIEW_CAPABILITY_TOKEN_EXPOSED = "VIEW_CAPABILITY_TOKEN_EXPOSED"
    VIEW_DELIVERY_MODE_INVALID = "VIEW_DELIVERY_MODE_INVALID"

    # WP-VLT0 Access event ledger
    ACCESS_LEDGER_SEQUENCE_CONFLICT = "ACCESS_LEDGER_SEQUENCE_CONFLICT"
    ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH = "ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH"
    ACCESS_LEDGER_TAMPERED = "ACCESS_LEDGER_TAMPERED"
    ACCESS_LEDGER_APPEND_ONLY_VIOLATION = "ACCESS_LEDGER_APPEND_ONLY_VIOLATION"
    ACCESS_EVENT_HASH_MISMATCH = "ACCESS_EVENT_HASH_MISMATCH"

    # WP-VLT0 Artifact seal protocol
    SEAL_LIVE_WRITER_STILL_ACTIVE = "SEAL_LIVE_WRITER_STILL_ACTIVE"
    SEAL_PARTIAL_INCOMPLETE = "SEAL_PARTIAL_INCOMPLETE"
    SEAL_ALREADY_SEALED = "SEAL_ALREADY_SEALED"
    SEAL_MANIFEST_HASH_MISMATCH = "SEAL_MANIFEST_HASH_MISMATCH"
    SEAL_COMMIT_INTENT_MISSING = "SEAL_COMMIT_INTENT_MISSING"
    SEAL_FENCE_STALE = "SEAL_FENCE_STALE"

    # WP-VLT0 CAS/DB reconcile
    RECONCILE_LIVE_WRITER_ACTIVE = "RECONCILE_LIVE_WRITER_ACTIVE"
    RECONCILE_PARTIAL_WRITER_DEAD = "RECONCILE_PARTIAL_WRITER_DEAD"
    RECONCILE_SEALED_DB_UNCOMMITTED = "RECONCILE_SEALED_DB_UNCOMMITTED"
    RECONCILE_DB_COMMITTED_ARTIFACT_MISSING = "RECONCILE_DB_COMMITTED_ARTIFACT_MISSING"
    RECONCILE_HASH_MISMATCH = "RECONCILE_HASH_MISMATCH"
    RECONCILE_CONFLICT = "RECONCILE_CONFLICT"
    RECONCILE_MISSING = "RECONCILE_MISSING"

    # WP-VLT0 CAS core reuse enforcement
    VAULT_SECOND_STORE_REJECTED = "VAULT_SECOND_STORE_REJECTED"

    # WP-IN1 CandidateManifest / Exporter — 只读 intake
    IN1_PRODUCTION_WRITE_REJECTED = "IN1_PRODUCTION_WRITE_REJECTED"
    IN1_PRODUCER_SCHEMA_NOT_FROZEN = "IN1_PRODUCER_SCHEMA_NOT_FROZEN"
    IN1_ROOT_HASH_MISMATCH = "IN1_ROOT_HASH_MISMATCH"
    IN1_EXPORT_MANIFEST_HASH_MISMATCH = "IN1_EXPORT_MANIFEST_HASH_MISMATCH"
    IN1_ATTEMPT_REF_HASH_MISMATCH = "IN1_ATTEMPT_REF_HASH_MISMATCH"
    IN1_MISSING_ARTIFACT = "IN1_MISSING_ARTIFACT"
    IN1_SOURCE_ROOT_DRIFT = "IN1_SOURCE_ROOT_DRIFT"
    IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT = "IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT"
    IN1_MUTABLE_REFERENCE_REJECTED = "IN1_MUTABLE_REFERENCE_REJECTED"
    IN1_PRODUCER_BUNDLE_INVALID = "IN1_PRODUCER_BUNDLE_INVALID"

    # WP-HG0 HumanGate — actor / roster / gate type
    ACTOR_NOT_IN_ROSTER = "ACTOR_NOT_IN_ROSTER"
    ACTOR_INACTIVE = "ACTOR_INACTIVE"
    ACTOR_TYPE_INVALID = "ACTOR_TYPE_INVALID"
    ACTOR_ROLE_MISSING = "ACTOR_ROLE_MISSING"
    GATE_TYPE_UNKNOWN = "GATE_TYPE_UNKNOWN"
    GATE_REQUIRED_ROLE_MISSING = "GATE_REQUIRED_ROLE_MISSING"
    GATE_REQUIRED_SIGNATURES_NOT_MET = "GATE_REQUIRED_SIGNATURES_NOT_MET"
    GATE_SELF_APPROVAL_REJECTED = "GATE_SELF_APPROVAL_REJECTED"
    GATE_DUTY_CONFLICT = "GATE_DUTY_CONFLICT"
    GATE_DECISION_UNSIGNED = "GATE_DECISION_UNSIGNED"
    GATE_DECISION_HASH_MISMATCH = "GATE_DECISION_HASH_MISMATCH"
    GATE_PAYLOAD_HASH_MISMATCH = "GATE_PAYLOAD_HASH_MISMATCH"
    GATE_REPLAY_DETECTED = "GATE_REPLAY_DETECTED"
    GATE_NONCE_INVALID = "GATE_NONCE_INVALID"

    # WP-HG0 HumanGate — key lifecycle
    KEY_NOT_REGISTERED = "KEY_NOT_REGISTERED"
    KEY_REVOKED = "KEY_REVOKED"
    KEY_EXPIRED = "KEY_EXPIRED"
    KEY_NOT_YET_VALID = "KEY_NOT_YET_VALID"
    KEY_ACTOR_MISMATCH = "KEY_ACTOR_MISMATCH"
    KEY_ROLE_NOT_ELIGIBLE = "KEY_ROLE_NOT_ELIGIBLE"

    # WP-HG0 HumanGate — GV0 consumption
    HG0_COMPLETION_CONTRACT_NOT_CONSUMED = "HG0_COMPLETION_CONTRACT_NOT_CONSUMED"
    HG0_STATE_COMMAND_REJECTED = "HG0_STATE_COMMAND_REJECTED"

    # WP-CW0 ModelRolePort / attempt / receipt / reconcile
    CW0_UNKNOWN_ROLE = "CW0_UNKNOWN_ROLE"
    CW0_ROLE_NOT_FROZEN = "CW0_ROLE_NOT_FROZEN"
    CW0_REGISTRY_HASH_MISMATCH = "CW0_REGISTRY_HASH_MISMATCH"
    CW0_ROLE_MISSING_REQUIRED_PROFILE = "CW0_ROLE_MISSING_REQUIRED_PROFILE"
    CW0_ROLE_MISSING_VIEW_POLICY = "CW0_ROLE_MISSING_VIEW_POLICY"
    CW0_ROLE_TOOL_POLICY_ALLOWS_TOOLS = "CW0_ROLE_TOOL_POLICY_ALLOWS_TOOLS"
    CW0_CONTRACT_HASH_MISMATCH = "CW0_CONTRACT_HASH_MISMATCH"
    CW0_CONTRACT_ROLE_MISMATCH = "CW0_CONTRACT_ROLE_MISMATCH"
    CW0_CONTRACT_PROFILE_MISMATCH = "CW0_CONTRACT_PROFILE_MISMATCH"
    CW0_CONTRACT_VIEW_POLICY_MISMATCH = "CW0_CONTRACT_VIEW_POLICY_MISMATCH"
    CW0_CONTRACT_TOOL_POLICY_MISMATCH = "CW0_CONTRACT_TOOL_POLICY_MISMATCH"
    CW0_CONTRACT_CAPABILITY_MISMATCH = "CW0_CONTRACT_CAPABILITY_MISMATCH"
    CW0_CONTRACT_ADAPTER_MISMATCH = "CW0_CONTRACT_ADAPTER_MISMATCH"

    # Attempt lifecycle
    ATTEMPT_UNKNOWN_START = "ATTEMPT_UNKNOWN_START"
    ATTEMPT_STALE_FENCE = "ATTEMPT_STALE_FENCE"
    ATTEMPT_SENSITIVE_SINK = "ATTEMPT_SENSITIVE_SINK"
    ATTEMPT_ILLEGAL_STATE_TRANSITION = "ATTEMPT_ILLEGAL_STATE_TRANSITION"
    ATTEMPT_NOT_ACCEPTED = "ATTEMPT_NOT_ACCEPTED"
    ATTEMPT_ALREADY_TERMINATED = "ATTEMPT_ALREADY_TERMINATED"
    ATTEMPT_NOT_STARTED = "ATTEMPT_NOT_STARTED"
    ATTEMPT_CANCELLED = "ATTEMPT_CANCELLED"
    ATTEMPT_TIMEOUT = "ATTEMPT_TIMEOUT"
    ATTEMPT_FENCE_TOKEN_MISMATCH = "ATTEMPT_FENCE_TOKEN_MISMATCH"
    ATTEMPT_RECEIPT_HASH_MISMATCH = "ATTEMPT_RECEIPT_HASH_MISMATCH"
    ATTEMPT_OUTPUT_SCHEMA_INVALID = "ATTEMPT_OUTPUT_SCHEMA_INVALID"
    ATTEMPT_DETERMINISM_VIOLATION = "ATTEMPT_DETERMINISM_VIOLATION"

    # Reconcile
    RECONCILE_UNKNOWN_START = "RECONCILE_UNKNOWN_START"
    RECONCILE_STALE_FENCE = "RECONCILE_STALE_FENCE"
    RECONCILE_SENSITIVE_SINK = "RECONCILE_SENSITIVE_SINK"
    RECONCILE_ILLEGAL_STATE = "RECONCILE_ILLEGAL_STATE"

    # WP-DB1I — Schema bootstrap / fenced apply / D-volume ledger
    DB1I_MIGRATION_SPEC_HASH_DRIFT = "DB1I_MIGRATION_SPEC_HASH_DRIFT"
    DB1I_PLAN_HASH_DRIFT = "DB1I_PLAN_HASH_DRIFT"
    DB1I_SITE_FINGERPRINT_MISMATCH = "DB1I_SITE_FINGERPRINT_MISMATCH"
    DB1I_DB1L_REPORT_MISSING = "DB1I_DB1L_REPORT_MISSING"
    DB1I_HUMAN_GATE_DECISION_MISSING = "DB1I_HUMAN_GATE_DECISION_MISSING"
    DB1I_HUMAN_GATE_DECISION_REJECTED = "DB1I_HUMAN_GATE_DECISION_REJECTED"
    DB1I_FENCE_MISSING = "DB1I_FENCE_MISSING"
    DB1I_FENCE_STALE = "DB1I_FENCE_STALE"
    DB1I_FENCE_DUPLICATE = "DB1I_FENCE_DUPLICATE"
    DB1I_DUPLICATE_APPLY = "DB1I_DUPLICATE_APPLY"
    DB1I_APPLY_WITHOUT_FENCE = "DB1I_APPLY_WITHOUT_FENCE"
    DB1I_UNKNOWN_OUTCOME = "DB1I_UNKNOWN_OUTCOME"
    DB1I_RESUME_CATALOG_MISMATCH = "DB1I_RESUME_CATALOG_MISMATCH"
    DB1I_LEDGER_TAMPERED = "DB1I_LEDGER_TAMPERED"
    DB1I_LEDGER_PREVIOUS_HASH_MISMATCH = "DB1I_LEDGER_PREVIOUS_HASH_MISMATCH"
    DB1I_IMPORT_ANCHOR_HASH_MISMATCH = "DB1I_IMPORT_ANCHOR_HASH_MISMATCH"
    DB1I_BOOTSTRAP_RECEIPT_HASH_MISMATCH = "DB1I_BOOTSTRAP_RECEIPT_HASH_MISMATCH"
    DB1I_SCHEMA_STATE_REPORT_INVALID = "DB1I_SCHEMA_STATE_REPORT_INVALID"
    DB1I_RUNTIME_CAPABILITY_NOT_ALLOWED = "DB1I_RUNTIME_CAPABILITY_NOT_ALLOWED"
    DB1I_RECONCILE_CAPABILITY_NOT_ALLOWED = "DB1I_RECONCILE_CAPABILITY_NOT_ALLOWED"
    DB1I_PERMIT_MISMATCH = "DB1I_PERMIT_MISMATCH"
    DB1I_ACTION_OUT_OF_RANGE = "DB1I_ACTION_OUT_OF_RANGE"

    # WP-CW-D1 DevinCliModelRoleAdapter — profile / parser / capability
    CWD1_MODEL_UID_MISMATCH = "CWD1_MODEL_UID_MISMATCH"
    CWD1_EFFORT_MISMATCH = "CWD1_EFFORT_MISMATCH"
    CWD1_EFFORT_ENCODING_INVALID = "CWD1_EFFORT_ENCODING_INVALID"
    CWD1_PROFILE_DRIFT = "CWD1_PROFILE_DRIFT"
    CWD1_ATIF_PARSE_FAILED = "CWD1_ATIF_PARSE_FAILED"
    CWD1_ATIF_GENERATION_MODEL_MISSING = "CWD1_ATIF_GENERATION_MODEL_MISSING"
    CWD1_ATIF_TOOL_EVENT_DETECTED = "CWD1_ATIF_TOOL_EVENT_DETECTED"
    CWD1_CATALOG_SNAPSHOT_MISSING = "CWD1_CATALOG_SNAPSHOT_MISSING"
    CWD1_REASONING_MODE_UNOBSERVABLE = "CWD1_REASONING_MODE_UNOBSERVABLE"

    # WP-CW-C1 CodexExecModelRoleAdapter — profile / parser / capability
    CWC1_MODEL_MISMATCH = "CWC1_MODEL_MISMATCH"
    CWC1_EFFORT_MISMATCH = "CWC1_EFFORT_MISMATCH"
    CWC1_MODE_MISMATCH = "CWC1_MODE_MISMATCH"
    CWC1_ORCHESTRATION_MISMATCH = "CWC1_ORCHESTRATION_MISMATCH"
    CWC1_PROFILE_DRIFT = "CWC1_PROFILE_DRIFT"
    CWC1_JSONL_PARSE_FAILED = "CWC1_JSONL_PARSE_FAILED"
    CWC1_JSONL_EVENT_GAP = "CWC1_JSONL_EVENT_GAP"
    CWC1_JSONL_NO_TERMINAL = "CWC1_JSONL_NO_TERMINAL"
    CWC1_JSONL_TOOL_EVENT_DETECTED = "CWC1_JSONL_TOOL_EVENT_DETECTED"
    CWC1_CHILD_USAGE_MISSING = "CWC1_CHILD_USAGE_MISSING"
    CWC1_ARGUMENT_MAPPING_MISSING = "CWC1_ARGUMENT_MAPPING_MISSING"

    # Profile capability report — cross-adapter
    PROFILE_REQUESTED_EFFECTIVE_MISMATCH = "PROFILE_REQUESTED_EFFECTIVE_MISMATCH"
    PROFILE_UNOBSERVABLE_FIELD_NOT_DECLARED = "PROFILE_UNOBSERVABLE_FIELD_NOT_DECLARED"
    PROFILE_REQUIRED_FIELD_MISSING = "PROFILE_REQUIRED_FIELD_MISSING"
    PROFILE_ADAPTER_KIND_MISMATCH = "PROFILE_ADAPTER_KIND_MISMATCH"
    PROFILE_TOOL_POLICY_VIOLATION = "PROFILE_TOOL_POLICY_VIOLATION"
    PROFILE_VIEW_POLICY_VIOLATION = "PROFILE_VIEW_POLICY_VIOLATION"

    # Bypass tests — adapter must NOT use solver_harness / repo workspace / tool events
    BYPASS_SOLVER_HARNESS_USED = "BYPASS_SOLVER_HARNESS_USED"
    BYPASS_REPO_WORKSPACE_USED = "BYPASS_REPO_WORKSPACE_USED"
    BYPASS_TOOL_EVENT_DETECTED = "BYPASS_TOOL_EVENT_DETECTED"

    # WP-RT1 Runtime — WorkEvent / lease / outbox / commit / reconcile / checkpoint
    WORK_EVENT_SEQUENCE_GAP = "WORK_EVENT_SEQUENCE_GAP"
    WORK_EVENT_PREVIOUS_HASH_MISMATCH = "WORK_EVENT_PREVIOUS_HASH_MISMATCH"
    WORK_EVENT_APPEND_ONLY_VIOLATION = "WORK_EVENT_APPEND_ONLY_VIOLATION"
    WORK_EVENT_PAYLOAD_HASH_MISMATCH = "WORK_EVENT_PAYLOAD_HASH_MISMATCH"
    WORK_EVENT_FENCE_MISMATCH = "WORK_EVENT_FENCE_MISMATCH"
    WORK_EVENT_DUPLICATE_EVENT_ID = "WORK_EVENT_DUPLICATE_EVENT_ID"

    LEASE_NOT_FOUND = "LEASE_NOT_FOUND"
    LEASE_ALREADY_HELD = "LEASE_ALREADY_HELD"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    LEASE_STALE_FENCE = "LEASE_STALE_FENCE"
    LEASE_RENEW_FENCE_MISMATCH = "LEASE_RENEW_FENCE_MISMATCH"
    LEASE_RELEASE_FENCE_MISMATCH = "LEASE_RELEASE_FENCE_MISMATCH"

    OUTBOX_DUPLICATE_KEY = "OUTBOX_DUPLICATE_KEY"
    OUTBOX_NOT_FOUND = "OUTBOX_NOT_FOUND"
    OUTBOX_ALREADY_DELIVERED = "OUTBOX_ALREADY_DELIVERED"
    OUTBOX_REDELIVERY_REJECTED = "OUTBOX_REDELIVERY_REJECTED"
    OUTBOX_TRANSACTION_NOT_ATOMIC = "OUTBOX_TRANSACTION_NOT_ATOMIC"

    COMMIT_INTENT_EXPIRED = "COMMIT_INTENT_EXPIRED"
    COMMIT_INTENT_REVOKED = "COMMIT_INTENT_REVOKED"
    COMMIT_INTENT_ALREADY_CONSUMED = "COMMIT_INTENT_ALREADY_CONSUMED"
    COMMIT_INTENT_INPUT_HASH_DRIFT = "COMMIT_INTENT_INPUT_HASH_DRIFT"
    COMMIT_INTENT_MANIFEST_HASH_MISMATCH = "COMMIT_INTENT_MANIFEST_HASH_MISMATCH"
    COMMIT_INTENT_FENCE_STALE = "COMMIT_INTENT_FENCE_STALE"
    COMMIT_INTENT_PERMIT_REVOKED = "COMMIT_INTENT_PERMIT_REVOKED"

    RUNTIME_REDIS_PROJECTION_LOST = "RUNTIME_REDIS_PROJECTION_LOST"
    RUNTIME_REDIS_REBUILD_HASH_MISMATCH = "RUNTIME_REDIS_REBUILD_HASH_MISMATCH"
    RUNTIME_CHECKPOINT_HASH_MISMATCH = "RUNTIME_CHECKPOINT_HASH_MISMATCH"
    RUNTIME_CHECKPOINT_INCOMPLETE = "RUNTIME_CHECKPOINT_INCOMPLETE"
    RUNTIME_RECOVERY_FAILED = "RUNTIME_RECOVERY_FAILED"
    RUNTIME_SCHEMA_STATE_REPORT_REISSUED = "RUNTIME_SCHEMA_STATE_REPORT_REISSUED"
    RUNTIME_INPUT_HASH_DRIFT = "RUNTIME_INPUT_HASH_DRIFT"

    # WP-QA0 Controlled Dual-Carrier Authoring — P3A chain / Bakeoff-A / bootstrap
    QA_BOOTSTRAP_INPUT_UNSIGNED = "QA_BOOTSTRAP_INPUT_UNSIGNED"
    QA_FILE_ONLY_LIVE_BYPASS = "QA_FILE_ONLY_LIVE_BYPASS"
    QA_CANONICAL_REPORT_MISSING = "QA_CANONICAL_REPORT_MISSING"
    QA_QUESTION_MODIFIED_DOWNSTREAM_NOT_INVALIDATED = "QA_QUESTION_MODIFIED_DOWNSTREAM_NOT_INVALIDATED"
    QA_AUTHOR_IDENTITY_LEAKED = "QA_AUTHOR_IDENTITY_LEAKED"
    QA_BARE_METRIC_SNEAKED = "QA_BARE_METRIC_SNEAKED"
    QA_RETRY_UNTIL_DESIRED = "QA_RETRY_UNTIL_DESIRED"
    QA_UNQUALIFIED_ROLE_ROUTED = "QA_UNQUALIFIED_ROLE_ROUTED"
    QA_DRAFT_NOT_APPEND_ONLY = "QA_DRAFT_NOT_APPEND_ONLY"
    QA_RELEASE_NOT_IMMUTABLE = "QA_RELEASE_NOT_IMMUTABLE"
    QA_GATE_NOT_SIGNED = "QA_GATE_NOT_SIGNED"
    QA_BRIEF_HASH_MISMATCH = "QA_BRIEF_HASH_MISMATCH"
    QA_MECHANISM_CONTRACT_CHANGED = "QA_MECHANISM_CONTRACT_CHANGED"
    QA_COVERAGE_CELL_CHANGED = "QA_COVERAGE_CELL_CHANGED"
    QA_BAKEOFF_A_USING_BARE = "QA_BAKEOFF_A_USING_BARE"
    QA_NO_SOLVER_ALLOWED = "QA_NO_SOLVER_ALLOWED"
    QA_NO_REDIS_ALLOWED = "QA_NO_REDIS_ALLOWED"
    QA_BAKEOFF_A_METRIC_NOT_ALLOWED = "QA_BAKEOFF_A_METRIC_NOT_ALLOWED"
    QA_INVALIDATION_TARGET_UNKNOWN = "QA_INVALIDATION_TARGET_UNKNOWN"
    QA_STATE_TRANSITION_ILLEGAL = "QA_STATE_TRANSITION_ILLEGAL"
    QA_ROLE_ROUTING_NOT_FROZEN = "QA_ROLE_ROUTING_NOT_FROZEN"
    QA_EVALUATION_PACK_NOT_FROZEN = "QA_EVALUATION_PACK_NOT_FROZEN"
    QA_BOOTSTRAP_DEPENDS_ON_CASEPACK = "QA_BOOTSTRAP_DEPENDS_ON_CASEPACK"
    QA_REVIEW_KIND_UNKNOWN = "QA_REVIEW_KIND_UNKNOWN"
    QA_DRAFT_HASH_MISMATCH = "QA_DRAFT_HASH_MISMATCH"
    QA_REVIEW_HASH_MISMATCH = "QA_REVIEW_HASH_MISMATCH"
    QA_VERIFICATION_DOSSIER_HASH_MISMATCH = "QA_VERIFICATION_DOSSIER_HASH_MISMATCH"
    QA_RELEASE_HASH_MISMATCH = "QA_RELEASE_HASH_MISMATCH"
    QA_RELEASE_WITHOUT_BOTH_REVIEWS = "QA_RELEASE_WITHOUT_BOTH_REVIEWS"
    QA_OUTPUT_KIND_FORBIDDEN = "QA_OUTPUT_KIND_FORBIDDEN"

    # WP-SV1 TargetSolver/Harness — bypass / trajectory / answer / policy / fence
    SV_DIRECT_DEVIN_BYPASS = "SV_DIRECT_DEVIN_BYPASS"
    SV_TOOL_EVENT_DETECTED = "SV_TOOL_EVENT_DETECTED"
    SV_TRAJECTORY_MISSING = "SV_TRAJECTORY_MISSING"
    SV_REPO_WORKSPACE_NOT_ISOLATED = "SV_REPO_WORKSPACE_NOT_ISOLATED"
    SV_ANSWER_NOT_ISOLATED = "SV_ANSWER_NOT_ISOLATED"
    SV_NOTOOL_VIOLATION = "SV_NOTOOL_VIOLATION"
    SV_LAUNCH_RECEIPT_INCOMPLETE = "SV_LAUNCH_RECEIPT_INCOMPLETE"
    SV_HARNESS_PROFILE_HASH_MISMATCH = "SV_HARNESS_PROFILE_HASH_MISMATCH"
    SV_FENCE_TOKEN_INVALID = "SV_FENCE_TOKEN_INVALID"
    SV_PREPARED_JOB_HASH_DRIFT = "SV_PREPARED_JOB_HASH_DRIFT"
    SV_CANCEL_AFTER_TERMINAL = "SV_CANCEL_AFTER_TERMINAL"
    SV_RECONCILE_FENCE_MISMATCH = "SV_RECONCILE_FENCE_MISMATCH"
    SV_BUDGET_EXCEEDED = "SV_BUDGET_EXCEEDED"
    SV_TERMINAL_REASON_INVALID = "SV_TERMINAL_REASON_INVALID"
    SV_LAUNCH_STATE_INVALID = "SV_LAUNCH_STATE_INVALID"
    SV_IDEMPOTENCY_KEY_CONFLICT = "SV_IDEMPOTENCY_KEY_CONFLICT"
    SV_PROBLEM_REF_HASH_MISMATCH = "SV_PROBLEM_REF_HASH_MISMATCH"
    SV_VIEW_REF_HASH_MISMATCH = "SV_VIEW_REF_HASH_MISMATCH"
    SV_BUDGET_CONTRACT_INVALID = "SV_BUDGET_CONTRACT_INVALID"
    SV_TOOL_POLICY_KIND_INVALID = "SV_TOOL_POLICY_KIND_INVALID"
    SV_TRAJECTORY_KIND_INVALID = "SV_TRAJECTORY_KIND_INVALID"
    SV_ANSWER_KIND_INVALID = "SV_ANSWER_KIND_INVALID"
    SV_OUTPUT_KIND_FORBIDDEN = "SV_OUTPUT_KIND_FORBIDDEN"
    SV_CAPABILITY_KIND_INVALID = "SV_CAPABILITY_KIND_INVALID"
    SV_SAFE_LAUNCH_VERDICT_FAIL = "SV_SAFE_LAUNCH_VERDICT_FAIL"
    SV_ANSWER_ISOLATION_VERDICT_FAIL = "SV_ANSWER_ISOLATION_VERDICT_FAIL"
    SV_NOTOOL_REPORT_VERDICT_FAIL = "SV_NOTOOL_REPORT_VERDICT_FAIL"
    SV_HARNESS_REPORT_VERDICT_FAIL = "SV_HARNESS_REPORT_VERDICT_FAIL"
    SV_OBSERVE_TICKET_UNKNOWN = "SV_OBSERVE_TICKET_UNKNOWN"
    SV_COLLECT_TICKET_UNKNOWN = "SV_COLLECT_TICKET_UNKNOWN"
    SV_PREPARE_JOB_INVALID = "SV_PREPARE_JOB_INVALID"
    SV_PREPARED_JOB_INVALID = "SV_PREPARED_JOB_INVALID"
    SV_LAUNCH_TICKET_INVALID = "SV_LAUNCH_TICKET_INVALID"
    SV_RECONCILE_UNKNOWN_ATTEMPT = "SV_RECONCILE_UNKNOWN_ATTEMPT"

    # WP-TX1 Taxonomy/Tell Registry — taxonomy snapshot / attribute dict / FCA
    TX_TAXONOMY_HASH_MISMATCH = "TX_TAXONOMY_HASH_MISMATCH"
    TX_TAXONOMY_VERSION_NOT_FROZEN = "TX_TAXONOMY_VERSION_NOT_FROZEN"
    TX_TAXONOMY_APPEND_ONLY_VIOLATED = "TX_TAXONOMY_APPEND_ONLY_VIOLATED"
    TX_TAXONOMY_SUPERSEDES_REF_BROKEN = "TX_TAXONOMY_SUPERSEDES_REF_BROKEN"
    TX_ATTRIBUTE_DICT_HASH_MISMATCH = "TX_ATTRIBUTE_DICT_HASH_MISMATCH"
    TX_ATTRIBUTE_DICT_VERSION_NOT_FROZEN = "TX_ATTRIBUTE_DICT_VERSION_NOT_FROZEN"
    TX_FCA_CONTEXT_MARKED_AS_TRUTH = "TX_FCA_CONTEXT_MARKED_AS_TRUTH"
    TX_FCA_CONTEXT_NOT_CALIBRATION_AID = "TX_FCA_CONTEXT_NOT_CALIBRATION_AID"

    # WP-TX1 — Tell manifestation / recognition / core / family
    TX_MANIFESTATION_EQUALS_CORE = "TX_MANIFESTATION_EQUALS_CORE"
    TX_MANIFESTATION_KIND_INVALID = "TX_MANIFESTATION_KIND_INVALID"
    TX_OBSERVATION_VIEW_KIND_INVALID = "TX_OBSERVATION_VIEW_KIND_INVALID"
    TX_TELL_RECOGNITION_TAXONOMY_REF_MISSING = "TX_TELL_RECOGNITION_TAXONOMY_REF_MISSING"
    TX_TELL_RECOGNITION_HASH_MISMATCH = "TX_TELL_RECOGNITION_HASH_MISMATCH"
    TX_TELL_CORE_INVARIANT_VIOLATED = "TX_TELL_CORE_INVARIANT_VIOLATED"
    TX_TELL_CORE_ACTION_INVALID = "TX_TELL_CORE_ACTION_INVALID"
    TX_TELL_CORE_NOT_FROZEN = "TX_TELL_CORE_NOT_FROZEN"
    TX_TELL_FAMILY_LINEAGE_BROKEN = "TX_TELL_FAMILY_LINEAGE_BROKEN"
    TX_TELL_FAMILY_LINEAGE_REF_MISSING = "TX_TELL_FAMILY_LINEAGE_REF_MISSING"

    # WP-TX1 — ApplicabilityBoundary
    TX_BOUNDARY_NEGATIVE_GUARD_VIOLATED = "TX_BOUNDARY_NEGATIVE_GUARD_VIOLATED"
    TX_BOUNDARY_GUARD_KIND_INVALID = "TX_BOUNDARY_GUARD_KIND_INVALID"
    TX_BOUNDARY_TRIGGER_MISSING = "TX_BOUNDARY_TRIGGER_MISSING"
    TX_BOUNDARY_BINDING_ROLE_INVALID = "TX_BOUNDARY_BINDING_ROLE_INVALID"

    # WP-TX1 — TellHintRelation (M:N)
    TX_HINT_RELATION_NOT_MN = "TX_HINT_RELATION_NOT_MN"
    TX_HINT_RELATION_KIND_INVALID = "TX_HINT_RELATION_KIND_INVALID"
    TX_HINT_RELATION_APPLICABILITY_MISSING = "TX_HINT_RELATION_APPLICABILITY_MISSING"

    # WP-TX1 — HintRenderer / HintInstance
    TX_HINT_RENDERER_HASH_MISMATCH = "TX_HINT_RENDERER_HASH_MISMATCH"
    TX_HINT_RENDERER_NOT_FROZEN = "TX_HINT_RENDERER_NOT_FROZEN"
    TX_HINT_INSTANCE_PAYLOAD_HASH_MISMATCH = "TX_HINT_INSTANCE_PAYLOAD_HASH_MISMATCH"
    TX_HINT_INSTANCE_RENDERER_REF_MISSING = "TX_HINT_INSTANCE_RENDERER_REF_MISSING"

    # WP-TX1 — SelectorDecision / InjectionPolicy
    TX_SELECTOR_DECISION_KIND_INVALID = "TX_SELECTOR_DECISION_KIND_INVALID"
    TX_SELECTOR_ABSTAIN_VIOLATED = "TX_SELECTOR_ABSTAIN_VIOLATED"
    TX_SELECTOR_RANKING_EMPTY = "TX_SELECTOR_RANKING_EMPTY"
    TX_INJECTION_POSITION_INVALID = "TX_INJECTION_POSITION_INVALID"
    TX_INJECTION_POLICY_VERSION_DRIFT = "TX_INJECTION_POLICY_VERSION_DRIFT"
    TX_INJECTION_POLICY_HASH_MISMATCH = "TX_INJECTION_POLICY_HASH_MISMATCH"

    # WP-TX1 — Progress / Termination / Critic / CompositionContract
    TX_CONTRACT_KIND_INVALID = "TX_CONTRACT_KIND_INVALID"
    TX_CONTRACT_HASH_MISMATCH = "TX_CONTRACT_HASH_MISMATCH"
    TX_COMPOSITION_CONTRACT_CYCLE = "TX_COMPOSITION_CONTRACT_CYCLE"
    TX_CRITIC_VERDICT_INVALID = "TX_CRITIC_VERDICT_INVALID"

    # WP-TX1 — TellStrategyRelease / lineage / pointer
    TX_RELEASE_HASH_MISMATCH = "TX_RELEASE_HASH_MISMATCH"
    TX_RELEASE_NOT_IMMUTABLE = "TX_RELEASE_NOT_IMMUTABLE"
    TX_RELEASE_LINEAGE_BROKEN = "TX_RELEASE_LINEAGE_BROKEN"
    TX_RELEASE_SUPERSEDES_REF_MISSING = "TX_RELEASE_SUPERSEDES_REF_MISSING"
    TX_RELEASE_STATE_INVALID = "TX_RELEASE_STATE_INVALID"
    TX_RELEASE_POINTER_CHANGED_BY_GATE = "TX_RELEASE_POINTER_CHANGED_BY_GATE"
    TX_RELEASE_COMPONENT_HASH_MISMATCH = "TX_RELEASE_COMPONENT_HASH_MISMATCH"
    TX_RELEASE_COMPONENT_MISSING = "TX_RELEASE_COMPONENT_MISSING"

    # WP-TX1 — MathValidity / SystemEfficacy
    TX_VALIDITY_STATUS_INVALID = "TX_VALIDITY_STATUS_INVALID"
    TX_VALIDITY_HASH_MISMATCH = "TX_VALIDITY_HASH_MISMATCH"
    TX_EFFICACY_STATUS_INVALID = "TX_EFFICACY_STATUS_INVALID"
    TX_EFFICACY_SOLVER_CONTEXT_MISSING = "TX_EFFICACY_SOLVER_CONTEXT_MISSING"
    TX_EFFICACY_HASH_MISMATCH = "TX_EFFICACY_HASH_MISMATCH"
    TX_EFFICACY_RENDERER_VERSION_DRIFT = "TX_EFFICACY_RENDERER_VERSION_DRIFT"
    TX_EFFICACY_SELECTOR_VERSION_DRIFT = "TX_EFFICACY_SELECTOR_VERSION_DRIFT"
    TX_EFFICACY_TARGET_SOLVER_VERSION_DRIFT = "TX_EFFICACY_TARGET_SOLVER_VERSION_DRIFT"

    # WP-TX1 — Evidence foreign key migration / invalidation
    TX_OLD_EVIDENCE_FOREIGN_KEY_NOT_MIGRATED = "TX_OLD_EVIDENCE_FOREIGN_KEY_NOT_MIGRATED"
    TX_INVALIDATION_TARGET_UNKNOWN = "TX_INVALIDATION_TARGET_UNKNOWN"
    TX_INVALIDATION_READJUDICATION_MISSING = "TX_INVALIDATION_READJUDICATION_MISSING"
    TX_INVALIDATION_EFFICACY_RETEST_MISSING = "TX_INVALIDATION_EFFICACY_RETEST_MISSING"

    # WP-CW1 Production Cognitive Workers — matrix / router / independence / lease
    CW_UNQUALIFIED_CELL_ROUTED = "CW_UNQUALIFIED_CELL_ROUTED"
    CW_SAME_SESSION_AUTHOR_REVIEWER = "CW_SAME_SESSION_AUTHOR_REVIEWER"
    CW_JUDGE_READ_UNAUTHORIZED_VIEW = "CW_JUDGE_READ_UNAUTHORIZED_VIEW"
    CW_FAKE_INDEPENDENCE_SAME_MODEL = "CW_FAKE_INDEPENDENCE_SAME_MODEL"
    CW_NO_FALLBACK_CARRIER = "CW_NO_FALLBACK_CARRIER"
    CW_CELL_CONCLUSION_MISSING = "CW_CELL_CONCLUSION_MISSING"
    CW_MATRIX_WILDCARD_REJECTED = "CW_MATRIX_WILDCARD_REJECTED"
    CW_MATRIX_HASH_MISMATCH = "CW_MATRIX_HASH_MISMATCH"
    CW_LEASE_ACQUIRE_FAILED = "CW_LEASE_ACQUIRE_FAILED"
    CW_RECONCILE_FENCE_MISMATCH = "CW_RECONCILE_FENCE_MISMATCH"
    CW_WORKER_NOT_INDEPENDENT = "CW_WORKER_NOT_INDEPENDENT"
    CW_CELL_COMPLETENESS_REMAINDER_NONZERO = "CW_CELL_COMPLETENESS_REMAINDER_NONZERO"
    CW_PROFILE_HASH_MISMATCH = "CW_PROFILE_HASH_MISMATCH"
    CW_ROLE_TYPE_UNKNOWN = "CW_ROLE_TYPE_UNKNOWN"
    CW_CELL_KEY_MISMATCH = "CW_CELL_KEY_MISMATCH"
    CW_CELL_VERDICT_INVALID = "CW_CELL_VERDICT_INVALID"
    CW_QUALIFICATION_SCOPE_INVALID = "CW_QUALIFICATION_SCOPE_INVALID"
    CW_CELL_EXPIRED = "CW_CELL_EXPIRED"
    CW_CELL_INVALIDATED = "CW_CELL_INVALIDATED"
    CW_BLINDING_VIOLATED = "CW_BLINDING_VIOLATED"
    CW_VIEW_POLICY_MISMATCH = "CW_VIEW_POLICY_MISMATCH"
    CW_OUTPUT_KIND_FORBIDDEN = "CW_OUTPUT_KIND_FORBIDDEN"
    CW_WORKER_SESSION_REUSE = "CW_WORKER_SESSION_REUSE"
    CW_MATRIX_SUPERSEDES_REF_INVALID = "CW_MATRIX_SUPERSEDES_REF_INVALID"
    CW_COMPLETENESS_SETS_NOT_DISJOINT = "CW_COMPLETENESS_SETS_NOT_DISJOINT"
    CW_COMPLETENESS_VERDICT_INVALID = "CW_COMPLETENESS_VERDICT_INVALID"

    # 通用
    OBJECT_HASH_MISMATCH = "OBJECT_HASH_MISMATCH"
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"


class VerificationError(Exception):
    """验证器返回的结构化错误。

    验证器不抛异常——它们返回 VerificationResult。
    本异常仅用于内部断言或 CLI 层转换。
    """

    def __init__(self, code: VerificationErrorCode, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}" if detail else code.value)


# 完成合同到期望 schema_id 的映射
COMPLETION_CONTRACT_TO_SCHEMA_ID: dict[str, str] = {
    "DOC_BOOTSTRAP_RECORD": "seven/docs/doc-bootstrap-completion-record",
    "IMPLEMENTATION_BUNDLE": "seven/implementation-completion-bundle",
    "AUDIT_RECORD": "seven/audit-record",
}

# 实施者允许的完成合同
IMPLEMENTER_CONTRACTS: frozenset[str] = frozenset(
    {"DOC_BOOTSTRAP_RECORD", "IMPLEMENTATION_BUNDLE"}
)

# 审计者允许的完成合同
AUDITOR_CONTRACTS: frozenset[str] = frozenset({"AUDIT_RECORD"})

# 实施者不能写的状态
IMPLEMENTER_FORBIDDEN_STATES: frozenset[str] = frozenset(
    {"AUDITED_PASS", "AUDITED_PARTIAL", "AUDITED_FAIL"}
)

# 合法的工作包状态全集
VALID_STATES: frozenset[str] = frozenset(
    {
        "NOT_STARTED",
        "READY",
        "IN_PROGRESS",
        "IMPLEMENTED_PENDING_EVIDENCE",
        "READY_FOR_AUDIT",
        "AUDITED_PASS",
        "AUDITED_PARTIAL",
        "AUDITED_FAIL",
        "BLOCKED",
    }
)

# 签名算法注册表 v1
SIGNATURE_ALGORITHM_V1: str = "Ed25519"

# 预留后端枚举
RESERVATION_BACKENDS: frozenset[str] = frozenset(
    {
        "DB_V2_OR_EQUIVALENT_TRANSACTIONAL_LEDGER",
        "SCHEMA_BOOTSTRAP_D_VOLUME_LEDGER",
        "SIDE_EFFECT_FREE_REFERENCE",  # GV0 自身的 side-effect-free 参考后端
    }
)

# 授权消费状态枚举
CONSUMPTION_STATUSES: frozenset[str] = frozenset(
    {"RESERVED", "CONSUMED", "RELEASED_UNUSED", "UNKNOWN_START_HELD", "QUARANTINED"}
)

# 授权模式枚举
AUTHORIZATION_MODES: frozenset[str] = frozenset(
    {"AUDITED_ACTIVATION", "UNAUDITED_AUTHORIZED_CANARY", "TRUST_ROOT_OR_SCHEMA_BOOTSTRAP"}
)

# 额度字段全集（用于守恒检查）
ALLOWANCE_FIELDS: tuple[str, ...] = (
    "invocations",
    "solver_launches",
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "human_gate_commits",
    "active_release_changes",
    "tokens",
    "cost_microunits",
)

# ─── WP-VLT0 Vault 常量 ────────────────────────────────────────────────

# Vault 敏感度级别（有序，从低到高）
SENSITIVITY_LEVELS: tuple[str, ...] = (
    "PUBLIC",
    "RESTRICTED",
    "SOLUTION_BEARING",
    "HOLDOUT_BEARING",
)

# Vault 允许的操作（READ_RAW_OBJECT 不在此列表中）
VAULT_OPERATIONS: frozenset[str] = frozenset(
    {"READ_DERIVED_VIEW", "DERIVE_VIEW", "WRITE_RESTRICTED_OBJECT", "SEAL_RESTRICTED_OBJECT"}
)

# 被拒绝的操作
FORBIDDEN_OPERATIONS: frozenset[str] = frozenset(
    {"READ_RAW_OBJECT"}
)

# Vault principal 类型
VAULT_PRINCIPAL_TYPES: frozenset[str] = frozenset(
    {"MODEL_ROLE", "TARGET_SOLVER", "HUMAN", "SERVICE", "AUDITOR"}
)

# AccessDecision 结果
ACCESS_DECISIONS: frozenset[str] = frozenset({"ALLOW", "DENY"})

# AccessEvent 结果
ACCESS_EVENT_RESULTS: frozenset[str] = frozenset(
    {"ACCESS_GRANTED", "ACCESS_DENIED", "DERIVATION_FAILED", "ACCESS_REVOKED", "ACCESS_QUARANTINED"}
)

# AccessDecision reason codes
ACCESS_REASON_CODES: frozenset[str] = frozenset(
    {
        "POLICY_ALLOW",
        "CAPABILITY_INVALID",
        "ISSUER_UNTRUSTED",
        "OUTSIDE_TIME_WINDOW",
        "PRINCIPAL_MISMATCH",
        "OPERATION_MISMATCH",
        "OBJECT_HASH_MISMATCH",
        "VIEW_HASH_MISMATCH",
        "SINK_MISMATCH",
        "NONCE_REPLAY",
        "REVOKED",
        "REVOCATION_UNKNOWN",
        "POLICY_DENY",
    }
)

# Check result 枚举
CHECK_RESULTS: frozenset[str] = frozenset({"PASS", "FAIL", "UNKNOWN"})

# 撤销状态枚举
REVOCATION_STATUSES: frozenset[str] = frozenset(
    {"ACTIVE", "REVOKED", "EXPIRED", "UNKNOWN"}
)

# Sink kind 枚举
SINK_KINDS: frozenset[str] = frozenset(
    {"EPHEMERAL_MODEL_INPUT", "RESTRICTED_VAULT", "RESTRICTED_CAS", "AUDIT_ONLY"}
)

# Artifact seal 状态
SEAL_STATES: frozenset[str] = frozenset(
    {"LIVE", "PARTIAL", "SEALED", "MISSING", "CONFLICT"}
)

# Reconcile 状态
RECONCILE_STATES: frozenset[str] = frozenset(
    {
        "LIVE_WRITER_ACTIVE",
        "PARTIAL_WRITER_DEAD",
        "SEALED_DB_UNCOMMITTED",
        "DB_COMMITTED_ARTIFACT_MISSING",
        "SEALED_AND_COMMITTED",
        "MISSING",
        "CONFLICT",
    }
)

# ─── WP-HG0 HumanGate 常量 ──────────────────────────────────────────────

# Actor 类型（谁可以参与 HumanGate）
ACTOR_TYPES: frozenset[str] = frozenset(
    {"HUMAN", "MODEL_ROLE", "SERVICE"}
)

# HumanGate 角色枚举
HUMAN_GATE_ROLES: frozenset[str] = frozenset(
    {
        "QUESTION_ARCHITECT",
        "ADVERSARIAL_EDITOR",
        "MATH_VERIFIER",
        "PROCESS_AUDITOR",
        "PROOF_JUDGE",
        "LEAKAGE_AUDITOR",
        "SELECTOR_RENDERER",
        "SITE_OWNER",
        "PROVISIONING_ACTOR",
    }
)

# Gate decision 结果枚举
GATE_DECISIONS: frozenset[str] = frozenset(
    {"APPROVE", "REJECT", "REQUEST_CHANGES", "QUARANTINE"}
)

# Gate verification status 枚举
GATE_VERIFICATION_STATUSES: frozenset[str] = frozenset(
    {"HUMAN_PENDING", "VERIFIED", "BLOCKED", "QUARANTINED"}
)

# Key lifecycle 状态枚举
KEY_STATUSES: frozenset[str] = frozenset(
    {"ACTIVE", "REVOKED", "EXPIRED", "PENDING"}
)

# HumanGate 签名 domain separator（含实际 NUL byte）
HUMAN_GATE_SIGNATURE_DOMAIN: str = "seven-human-gate-decision/v1\0"

# HumanGate signed_bytes_hash algorithm
HUMAN_GATE_HASH_ALGORITHM: str = "sha256(RFC8785-JCS-object-with-decision_hash-null)"

# ─── WP-CW0 ModelRolePort 常量 ──────────────────────────────────────────

# Attempt 状态枚举（有序状态机）
ATTEMPT_STATES: frozenset[str] = frozenset(
    {
        "CREATED",
        "ACCEPTED",
        "STARTED",
        "COMPLETED",
        "TERMINATED",
        "CANCELLED",
        "TIMED_OUT",
        "UNKNOWN_START_QUARANTINED",
    }
)

# 合法状态转换
ATTEMPT_TRANSITIONS: dict[str, frozenset[str]] = {
    "CREATED": frozenset({"ACCEPTED"}),
    "ACCEPTED": frozenset({"STARTED", "CANCELLED", "TIMED_OUT", "UNKNOWN_START_QUARANTINED"}),
    "STARTED": frozenset({"COMPLETED", "TERMINATED", "CANCELLED", "TIMED_OUT"}),
    "COMPLETED": frozenset(),  # 终态
    "TERMINATED": frozenset(),  # 终态
    "CANCELLED": frozenset(),  # 终态
    "TIMED_OUT": frozenset(),  # 终态
    "UNKNOWN_START_QUARANTINED": frozenset({"TERMINATED", "CANCELLED"}),
}

# 终态集合
ATTEMPT_TERMINAL_STATES: frozenset[str] = frozenset(
    {"COMPLETED", "TERMINATED", "CANCELLED", "TIMED_OUT"}
)

# Adapter 类型枚举
MODEL_ROLE_ADAPTER_KINDS: frozenset[str] = frozenset(
    {"FAKE", "DEVIN_CLI", "CODEX_EXEC", "OPENAI_RESPONSES"}
)

# Tool policy 枚举
TOOL_POLICY_KINDS: frozenset[str] = frozenset(
    {"NO_TOOLS", "READ_ONLY_TOOLS", "SANDBOXED_TOOLS"}
)

# View policy 枚举
VIEW_POLICY_KINDS: frozenset[str] = frozenset(
    {"PUBLIC_ONLY", "RESTRICTED_DERIVED", "SOLUTION_BEARING_DERIVED"}
)

# Output sink kind 枚举（attempt 输出目的地）
ATTEMPT_OUTPUT_SINK_KINDS: frozenset[str] = frozenset(
    {"EPHEMERAL_MODEL_OUTPUT", "RESTRICTED_VAULT", "AUDIT_ONLY"}
)

# Reconcile verdict 枚举
ATTEMPT_RECONCILE_VERDICTS: frozenset[str] = frozenset(
    {"CONSISTENT", "UNKNOWN_START", "STALE_FENCE", "SENSITIVE_SINK", "ILLEGAL_STATE"}
)

# RoleTypeRegistry 常量
ROLE_TYPE_REGISTRY_ID: str = "seven_model_role_types"
ROLE_TYPE_REGISTRY_SCHEMA_VERSION: str = "role_type_registry.v1"

# ─── WP-DB1I Schema bootstrap 常量 ──────────────────────────────────────

# Schema bootstrap ledger entry 类型（D 盘 append-only ledger）
SCHEMA_BOOTSTRAP_LEDGER_ENTRY_TYPES: frozenset[str] = frozenset(
    {
        "ACTION_INTENT",
        "ACTION_VERIFIED",
        "ACTION_FAILED",
        "UNKNOWN_OUTCOME",
        "FENCE_ACQUIRED",
        "FENCE_RELEASED",
    }
)

# Schema bootstrap action 状态
SCHEMA_BOOTSTRAP_ACTION_STATES: frozenset[str] = frozenset(
    {"PENDING", "INTENTED", "APPLIED", "VERIFIED", "FAILED", "UNKNOWN_OUTCOME"}
)

# Schema bootstrap fence 状态
SCHEMA_BOOTSTRAP_FENCE_STATES: frozenset[str] = frozenset(
    {"ACTIVE", "RELEASED", "EXPIRED", "SUPERSEDED"}
)

# DB1I 完成输出严格限定为这三类对象
DB1I_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "SchemaBootstrapImportAnchor",
    }
)

# DB1I 明确禁止输出的能力报告
DB1I_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
    }
)

# ─── WP-CW-D1 / WP-CW-C1 Adapter 常量 ──────────────────────────────────────

# Devin CLI 冻结 profile 字段
DEVIN_PROFILE_FIELDS: frozenset[str] = frozenset(
    {
        "carrier",
        "requested_cli_model_arg",
        "normalized_reasoning_effort",
        "effort_encoding",
        "reasoning_mode_request_semantics",
        "orchestration_request_semantics",
        "model_catalog_snapshot_ref_and_hash",
    }
)

# Devin CLI 冻结的 model UID（本机只读 catalog 观察）
DEVIN_FROZEN_MODEL_UID: str = "glm-5-2"
DEVIN_FROZEN_MODEL_DISPLAY: str = "GLM-5.2 High"
DEVIN_FROZEN_EFFORT: str = "high"
DEVIN_EFFORT_ENCODING: str = "model_uid"

# Codex CLI 冻结 profile 字段
CODEX_PROFILE_FIELDS: frozenset[str] = frozenset(
    {
        "carrier",
        "backend_kind",
        "requested_model",
        "model_alias_resolution_policy",
        "requested_reasoning_effort",
        "requested_reasoning_mode",
        "requested_orchestration_mode",
        "requested_service_tier",
        "sandbox_policy_ref_and_hash",
        "tool_policy_ref_and_hash",
        "network_policy_ref_and_hash",
        "output_schema_ref_and_hash",
        "cli_argument_mapping_ref_and_hash",
        "model_release_or_catalog_snapshot_ref_and_hash",
    }
)

# Codex CLI 冻结候选（NOT_TESTED，仅静态候选）
CODEX_FROZEN_MODEL: str = "gpt-5.6-sol"
CODEX_FROZEN_EFFORT: str = "xhigh"
CODEX_FROZEN_MODE: str = "standard"
CODEX_FROZEN_ORCHESTRATION: str = "single_agent"

# Profile capability report 中可声明为 UNOBSERVABLE 的字段
PROFILE_UNOBSERVABLE_FIELDS: frozenset[str] = frozenset(
    {
        "effective_reasoning_mode",
        "effective_orchestration_mode",
        "effective_effort",
    }
)

# Bypass test 名称枚举
BYPASS_TEST_NAMES: frozenset[str] = frozenset(
    {
        "direct_devin_bypass",
        "tool_event_test",
        "repo_workspace_test",
    }
)

# Bypass test 结果枚举
BYPASS_TEST_RESULTS: frozenset[str] = frozenset(
    {"PASS", "FAIL", "NOT_APPLICABLE"}
)

# ─── WP-RT1 Runtime 常量 ──────────────────────────────────────────────

# WorkEvent 类型枚举
WORK_EVENT_TYPES: frozenset[str] = frozenset(
    {
        "WORK_ITEM_STATE_CHANGED",
        "ARTIFACT_SEALED",
        "COMMIT_INTENT_RECORDED",
        "COMMIT_COMPLETED",
        "OUTBOX_APPENDED",
        "LEASE_ACQUIRED",
        "LEASE_RENEWED",
        "LEASE_RELEASED",
        "PERMIT_RESERVED",
        "PERMIT_CONSUMED",
        "PERMIT_RELEASED",
        "RECONCILE_COMPLETED",
        "CHECKPOINT_RECORDED",
    }
)

# Lease 状态枚举
LEASE_STATES: frozenset[str] = frozenset(
    {"ACTIVE", "RENEWED", "RELEASED", "EXPIRED", "SUPERSEDED"}
)

# Outbox 消息状态枚举
OUTBOX_STATES: frozenset[str] = frozenset(
    {"PENDING", "DELIVERED", "ACKED", "FAILED"}
)

# CommitIntent 状态枚举
COMMIT_INTENT_STATES: frozenset[str] = frozenset(
    {"PENDING", "CONSUMED", "REVOKED", "EXPIRED"}
)

# RT1 完成输出严格限定为这三类对象
RT1_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
        "RuntimeCheckpoint",
        "RuntimeRecoveryReceipt",
    }
)

# RT1 明确禁止输出的报告类型（属于 DB1I）
RT1_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "SchemaBootstrapImportAnchor",
    }
)

# Runtime reconcile 扩展状态（在 VLT0 RECONCILE_STATES 基础上增加）
RT1_RECONCILE_STATES: frozenset[str] = frozenset(
    {
        "LIVE_WRITER_ACTIVE",
        "PARTIAL_WRITER_DEAD",
        "SEALED_DB_UNCOMMITTED",
        "DB_COMMITTED_ARTIFACT_MISSING",
        "SEALED_AND_COMMITTED",
        "MISSING",
        "CONFLICT",
        "OUTBOX_UNPROJECTED",
        "OUTBOX_DUPLICATE_PROJECTED",
        "STALE_FENCE_LATE_COMMIT",
        "SEALED_OBJECT_TAMPERED",
        "COMMIT_INTENT_MISSING",
        "COMMIT_INTENT_EXPIRED",
        "COMMIT_INTENT_REVOKED",
        "PERMIT_OVERCONSUMED",
        "PERMIT_REPLAYED",
        "MULTIPLE_ATTEMPTS_CLAIM_SUCCESS",
    }
)

# RuntimeCheckpoint 状态
RUNTIME_CHECKPOINT_STATES: frozenset[str] = frozenset(
    {"RECORDED", "VERIFIED", "RECOVERED", "INCOMPLETE"}
)

# Redis projection 状态
REDIS_PROJECTION_STATES: frozenset[str] = frozenset(
    {"FRESH", "STALE", "LOST", "REBUILT"}
)

# ─── WP-SV1 TargetSolver/Harness 常量 ──────────────────────────────────

# Solver 终止原因枚举（trajectory/attempt 的合法 terminal reason）
SV_TERMINAL_REASONS: frozenset[str] = frozenset(
    {
        "COMPLETED",
        "CANCELLED",
        "TIMED_OUT",
        "BUDGET_EXCEEDED",
        "TERMINATED",
        "FAILED_PERMANENT",
        "QUARANTINED",
    }
)

# Solver tool policy 枚举（v1 只允许 NO_TOOL）
SV_TOOL_POLICY_KINDS: frozenset[str] = frozenset(
    {"NO_TOOL", "READ_ONLY_TOOLS", "SANDBOXED_TOOLS"}
)

# Solver 能力报告 kind 枚举（来自 CapabilityKindRegistry）
SV_CAPABILITY_KINDS: frozenset[str] = frozenset(
    {
        "TARGET_SOLVER_HARNESS",
        "TARGET_SOLVER_NO_TOOL",
        "TARGET_SOLVER_SAFE_LAUNCH",
        "TARGET_SOLVER_ANSWER_ISOLATION",
    }
)

# Solver launch 状态枚举（launch lifecycle）
SV_LAUNCH_STATES: frozenset[str] = frozenset(
    {
        "PREPARED",
        "LAUNCHED",
        "OBSERVED",
        "COLLECTED",
        "CANCELLED",
        "FAILED",
        "QUARANTINED",
    }
)

# Solver trajectory kind 枚举
SV_TRAJECTORY_KINDS: frozenset[str] = frozenset(
    {"FULL_TRAJECTORY", "PARTIAL_TRAJECTORY", "EMPTY_TRAJECTORY"}
)

# Solver answer kind 枚举
SV_ANSWER_KINDS: frozenset[str] = frozenset(
    {"FINAL_ANSWER", "PARTIAL_ANSWER", "NO_ANSWER"}
)

# SV1 完成输出严格限定为这些对象
SV_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "SolverHarnessCapabilityReport",
        "SolverNoToolCapabilityReport",
        "SolverSafeLaunchReport",
        "SolverAnswerIsolationReport",
        "SolverLaunchReceipt",
    }
)

# SV1 明确禁止输出的报告类型（属于其他工作包）
SV_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
    }
)

# ─── WP-QA0 Controlled Dual-Carrier Authoring 常量 ──────────────────────

# P3A 出题链状态机（有序：brief→architect→draft→adversarial_editor→math_verifier→gate→release）
QA_P3A_STATES: tuple[str, ...] = (
    "BRIEF_FROZEN",
    "ARCHITECT_ROUTED",
    "DRAFT_PRODUCED",
    "ADVERSARIAL_REVIEW_DONE",
    "MATH_VERIFICATION_DONE",
    "GATE_RELEASE_SIGNED",
    "QUESTION_RELEASED",
)

# P3A 合法状态转换
QA_P3A_TRANSITIONS: dict[str, frozenset[str]] = {
    "BRIEF_FROZEN": frozenset({"ARCHITECT_ROUTED"}),
    "ARCHITECT_ROUTED": frozenset({"DRAFT_PRODUCED"}),
    "DRAFT_PRODUCED": frozenset({"ADVERSARIAL_REVIEW_DONE"}),
    "ADVERSARIAL_REVIEW_DONE": frozenset({"MATH_VERIFICATION_DONE"}),
    "MATH_VERIFICATION_DONE": frozenset({"GATE_RELEASE_SIGNED"}),
    "GATE_RELEASE_SIGNED": frozenset({"QUESTION_RELEASED"}),
    "QUESTION_RELEASED": frozenset(),  # 终态
}

# P3A 终态
QA_P3A_TERMINAL_STATES: frozenset[str] = frozenset({"QUESTION_RELEASED"})

# 出题链机器角色（与 RoleRegistry 中 question_architect/adversarial_editor/math_verifier 对齐）
QA_AUTHORING_ROLES: frozenset[str] = frozenset(
    {"question_architect", "adversarial_editor", "math_verifier"}
)

# 审查种类（AdversarialReview / VerificationDossier 独立）
QA_REVIEW_KINDS: frozenset[str] = frozenset(
    {"ADVERSARIAL_REVIEW", "MATH_VERIFICATION"}
)

# Bakeoff-A 评估指标全集（作者身份隐去；不含 bare 指标）
QA_BAKEOFF_A_METRICS: frozenset[str] = frozenset(
    {
        "math_correct",
        "mechanism_faithful",
        "orthogonal_distance",
        "shortcut_leakage",
        "diversity",
        "human_revision_amount",
        "cost",
    }
)

# Bakeoff-A 明确禁止的指标（bare 维度属于 Bakeoff-B，不得偷入 A）
QA_BAKEOFF_A_FORBIDDEN_METRICS: frozenset[str] = frozenset(
    {
        "bare_correct",
        "bare_pass",
        "bare_baseline",
        "bare_qualification",
        "target_solver_result",
    }
)

# 失效传播目标（题面变化 → 这些下游全部失效）
QA_INVALIDATION_TARGETS: frozenset[str] = frozenset(
    {
        "AdversarialReview",
        "VerificationDossier",
        "QuestionRelease",
        "BareBaseline",
        "BareQualificationResult",
        "CaseRoleAssignment",
        "AuthoringEvaluationPack",
    }
)

# QA0 允许的输出对象种类
QA_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "MechanismContract",
        "CoverageCell",
        "AuthoringBrief",
        "QuestionDraftVersion",
        "AdversarialReview",
        "VerificationDossier",
        "QuestionRelease",
        "AuthoringEvaluationPack",
        "AuthoringBootstrapInputPack",
        "AuthoringCapabilityReport",
        "BakeoffAScoringReport",
    }
)

# QA0 明确禁止输出的对象种类（属于其他工作包，不得偷入）
QA_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "TargetSolverRunArtifact",
        "BareBaseline",
        "BareQualificationResult",
        "RedisProjection",
        "SolverDispatchReceipt",
        "CasePackVersion",
        "EvidenceRecord",
    }
)

# AuthoringBootstrapInputPack 状态
QA_BOOTSTRAP_STATES: frozenset[str] = frozenset(
    {"UNSIGNED", "SIGNED", "CONSUMED", "REVOKED"}
)

# AuthoringBakeoff-A 候选 carrier profile 标签（用于盲评 blinding）
QA_BAKEOFF_A_CARRIER_LABELS: frozenset[str] = frozenset(
    {"devin_glm_5_2_high", "codex_candidate", "other_profile"}
)

# QA0 能力报告 side-effect 键（必须全为 0）
QA_SIDE_EFFECT_KEYS: tuple[str, ...] = (
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "solver_launches",
    "model_live_calls",
    "human_gate_commits",
)

# QA0 gate 类型（G-Q-RELEASE）
QA_GATE_TYPE_Q_RELEASE: str = "G-Q-RELEASE"

# ─── WP-TX1 Taxonomy/Tell Registry 常量 ──────────────────────────────────

# TellManifestation kind 枚举——manifestation 是同一 latent Tell 在不同
# 观察粒度/trace 位置的显现，必须 NOT 等于 Core
TX_TELL_MANIFESTATION_KINDS: frozenset[str] = frozenset(
    {
        "TRACE_POSITION_MANIFESTATION",
        "OBSERVATION_GRANULARITY_MANIFESTATION",
        "SPAN_MANIFESTATION",
        "VIEW_MANIFESTATION",
    }
)

# TellCore cognitive action 枚举——Core 的不变认知动作
TX_TELL_CORE_ACTIONS: frozenset[str] = frozenset(
    {
        "BRANCH_OPEN",
        "BRANCH_CLOSE",
        "REDIRECT",
        "REINFORCE",
        "ABSTAIN",
    }
)

# ApplicabilityBoundary guard kind 枚举
TX_BOUNDARY_GUARD_KINDS: frozenset[str] = frozenset(
    {
        "NEGATIVE_GUARD",
        "POSITIVE_TRIGGER",
        "BINDING_ROLE_GUARD",
    }
)

# TellHintRelation kind 枚举——显式 M:N 边
TX_HINT_RELATION_KINDS: frozenset[str] = frozenset(
    {
        "TELL_TO_HINT",
        "HINT_TO_TELL",
        "BIDIRECTIONAL",
    }
)

# SelectorDecision kind 枚举
TX_SELECTOR_DECISION_KINDS: frozenset[str] = frozenset(
    {
        "SELECT",
        "RANK",
        "ABSTAIN",
        "FALLBACK",
    }
)

# Injection position 枚举
TX_INJECTION_POSITIONS: frozenset[str] = frozenset(
    {
        "PRE_TRACE",
        "AT_BRANCH_POINT",
        "MID_TRACE",
        "POST_TRACE",
    }
)

# Contract kind 枚举（Progress / Termination / Critic / Composition）
TX_CONTRACT_KINDS: frozenset[str] = frozenset(
    {
        "PROGRESS_CONTRACT",
        "TERMINATION_CONTRACT",
        "CRITIC_CONTRACT",
        "COMPOSITION_CONTRACT",
    }
)

# TellStrategyRelease 状态枚举
TX_RELEASE_STATES: frozenset[str] = frozenset(
    {"DRAFT", "RELEASED", "SUPERSEDED", "REVOKED"}
)

# MathValidityRecord 状态枚举
TX_VALIDITY_STATUSES: frozenset[str] = frozenset(
    {"VALID", "INVALID", "UNDETERMINED", "SUPERSEDED"}
)

# SystemEfficacyRecord 状态枚举
TX_EFFICACY_STATUSES: frozenset[str] = frozenset(
    {"EFFICACIOUS", "INEFFICACIOUS", "INCONCLUSIVE", "SUPERSEDED"}
)

# TaxonomySnapshot 状态枚举
TX_TAXONOMY_SNAPSHOT_STATES: frozenset[str] = frozenset(
    {"FROZEN", "SUPERSEDED", "DEPRECATED"}
)

# TX1 完成输出严格限定为这些对象
TX1_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "TaxonomySnapshot",
        "AttributeDictionaryVersion",
        "FCAContextSnapshot",
        "ObservationView",
        "TellManifestation",
        "TellRecognitionRecord",
        "TellFamily",
        "TellCore",
        "ApplicabilityBoundary",
        "TellHintRelation",
        "HintRenderer",
        "HintInstance",
        "SelectorDecision",
        "InjectionPolicy",
        "ProgressContract",
        "TerminationContract",
        "CriticContract",
        "CompositionContract",
        "TellStrategyRelease",
        "MathValidityRecord",
        "SystemEfficacyRecord",
    }
)

# TX1 明确禁止输出的对象种类（属于其他工作包，不得偷入）
TX1_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
        "SolverLaunchReceipt",
        "QuestionRelease",
        "EvidenceRecord",
        "RunAudit",
    }
)

# TX1 能力报告 side-effect 键（必须全为 0）
TX1_SIDE_EFFECT_KEYS: tuple[str, ...] = (
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "solver_launches",
    "model_live_calls",
    "human_gate_commits",
)

# Evidence foreign key 继承 scope 枚举
TX_EVIDENCE_INHERITANCE_SCOPES: frozenset[str] = frozenset(
    {"EXACT", "SUBSCOPE", "PROVENANCE_ONLY", "NONE"}
)

# Invalidation target 枚举——MechanismContract core/boundary 变化触发
TX_INVALIDATION_TARGETS: frozenset[str] = frozenset(
    {
        "CoverageApplicability",
        "CaseApplicability",
        "SystemEfficacyRecord",
        "CostEvidence",
        "MathValidityRecord",
    }
)

# TX1 gate 类型（G-TX-RELEASE）
TX_GATE_TYPE_TX_RELEASE: str = "G-TX-RELEASE"

# ─── WP-CW1 Production Cognitive Workers 常量 ──────────────────────────

# P3N 自然题审查角色（Trace/Solution/Adjudicator）
CW_P3N_ROLES: frozenset[str] = frozenset(
    {"trace_analyst", "solution_analyst", "adjudicator"}
)

# P6 独立三审角色（Process Auditor / Proof Judge / Leakage Auditor）
CW_P6_ROLES: frozenset[str] = frozenset(
    {"process_auditor", "proof_judge", "leakage_auditor"}
)

# Cell verdict 枚举（来自 role-qualification-matrix.v1.schema.json）
CW_CELL_STATUSES: frozenset[str] = frozenset(
    {"NOT_TESTED", "PASS", "PARTIAL", "FAIL", "BLOCKED", "EXPIRED"}
)

# Cell 结论集合（PASS / NOT_TESTED / FAILED — 缺失任一为 blocker）
CW_CELL_CONCLUSIONS: frozenset[str] = frozenset(
    {"PASS", "NOT_TESTED", "FAILED"}
)

# 完备性集合种类（completeness tracks required/pass/not-tested/failed/extra/missing/remainder）
CW_COMPLETENESS_KINDS: frozenset[str] = frozenset(
    {
        "required_cell_keys",
        "pass_cell_keys",
        "not_tested_cell_keys",
        "failed_cell_keys",
        "extra_cell_keys",
        "missing_cell_keys",
        "remainder_cell_keys",
    }
)

# 独立性种类
CW_INDEPENDENCE_KINDS: frozenset[str] = frozenset(
    {
        "DIFFERENT_SESSION",
        "DIFFERENT_MODEL",
        "DIFFERENT_CARRIER",
        "BLINDED_VIEW",
        "SAME_MODEL_FRESH_SESSION",
    }
)

# CW1 允许的输出对象种类
CW_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "MechanismContract",
        "RelationMapping",
        "MathVerificationRecord",
        "AdversarialShortcutReview",
        "NaturalCaseReviewBundle",
        "RunAudit",
        "ProcessAuditRecord",
        "ProofJudgmentRecord",
        "LeakageAuditRecord",
        "CognitiveWorkerCapabilityReport",
    }
)

# CW1 明确禁止输出的对象种类（属于其他工作包）
CW_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
        "TargetSolverRunArtifact",
        "SolverDispatchReceipt",
        "RedisProjection",
        "RuntimeCheckpoint",
    }
)

# Router 决策枚举
CW_ROUTER_DECISIONS: frozenset[str] = frozenset(
    {"DISPATCH", "BLOCK", "BLOCK_UNQUALIFIED", "BLOCK_NO_PASS_CELL", "BLOCK_EXPIRED"}
)

# 资格 scope 枚举
CW_QUALIFICATION_SCOPES: frozenset[str] = frozenset(
    {"CANARY", "PRODUCTION"}
)

# 被拒绝的通配符哨兵
CW_WILDCARD_SENTINELS: frozenset[str] = frozenset(
    {"*", "?", "ANY", "ALL", "DEFAULT", "any", "all", "default"}
)

# CW1 能力报告 side-effect 键（必须全为 0）
CW_SIDE_EFFECT_KEYS: tuple[str, ...] = (
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "solver_launches",
    "model_live_calls",
    "human_gate_commits",
)

# CW1 能力报告 check IDs
CW_CHECK_IDS: tuple[str, ...] = (
    "cw1.matrix.role_qualification_matrix_build",
    "cw1.matrix.cell_key_canonical",
    "cw1.matrix.wildcard_rejected",
    "cw1.matrix.completeness_remainder_zero",
    "cw1.router.production_pass_cell_required",
    "cw1.router.no_fallback_carrier",
    "cw1.router.unqualified_cell_blocked",
    "cw1.p3n.independent_sessions",
    "cw1.p6.blinding_enforced",
    "cw1.p6.judge_unauthorized_view_blocked",
    "cw1.independence.same_session_blocked",
    "cw1.independence.fake_independence_same_model_blocked",
    "cw1.lease.db_lease_acquire",
    "cw1.lease.reconcile_fence_match",
    "cw1.boundary_no_solver_or_schema_report",
)

# CW1 claims
CW_CLAIMS: tuple[str, ...] = (
    "role_qualification_matrix_build_verified",
    "cell_key_canonical_sha256",
    "wildcard_sentinels_rejected",
    "completeness_remainder_zero_when_pass",
    "production_dispatch_requires_pass_cell",
    "no_fallback_to_another_carrier",
    "unqualified_cell_routed_blocked",
    "p3n_independent_sessions_enforced",
    "p6_blinding_enforced",
    "judge_unauthorized_view_blocked",
    "same_session_author_reviewer_blocked",
    "fake_independence_same_model_blocked",
    "db_lease_acquire_via_rt1",
    "reconcile_fence_match_via_rt1",
    "does_not_produce_solver_or_schema_report",
)

# CW1 explicit nonclaims
CW_NONCLAIMS: tuple[str, ...] = (
    "does_not_prove_live_model_capability",
    "does_not_prove_solver_dispatch_capability",
    "does_not_connect_to_arangodb_in_test_suite",
    "does_not_authorize_live_canary_or_solver_dispatch",
    "does_not_prove_db_write_capability",
)
