"""GV0 固定错误码。

所有验证器返回结构化错误，不 TypeError 崩溃或跳过检查。
错误码是稳定枚举，下游消费者和审计者按码匹配，不按文本匹配。
"""

from __future__ import annotations

from enum import Enum


class VerificationErrorCode(str, Enum):
    """CompletionContractVerifier 和 SecurityContractVerifier 的固定错误码。"""

    # CompletionContractVerifier — owner / contract / schema / actor
    COMPLETION_CONTRACT_MISMATCH = "COMPLETION_CONTRACT_MISMATCH"
    ACTOR_NOT_AUTHORIZED = "ACTOR_NOT_AUTHORIZED"
    UNKNOWN_WORK_PACKAGE = "UNKNOWN_WORK_PACKAGE"
    SCHEMA_ID_MISMATCH = "SCHEMA_ID_MISMATCH"
    DAG_HASH_MISMATCH = "DAG_HASH_MISMATCH"
    DAG_LOAD_FAILED = "DAG_LOAD_FAILED"
    STATE_COMMAND_REJECTED = "STATE_COMMAND_REJECTED"

    # SecurityContractVerifier — 签名 / 授权链 / 额度
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    SIGNATURE_ALGORITHM_INVALID = "SIGNATURE_ALGORITHM_INVALID"
    SIGNATURE_DOMAIN_INVALID = "SIGNATURE_DOMAIN_INVALID"
    TIME_WINDOW_INVALID = "TIME_WINDOW_INVALID"
    TIME_NOT_CANONICAL_UTC = "TIME_NOT_CANONICAL_UTC"

    EEA_MODE_BINDING_INVALID = "EEA_MODE_BINDING_INVALID"
    EEA_ZERO_BUDGET = "EEA_ZERO_BUDGET"
    ACTION_REGISTRY_MISMATCH = "ACTION_REGISTRY_MISMATCH"

    PERMIT_ESCALATES_PARENT = "PERMIT_ESCALATES_PARENT"
    PERMIT_PARENT_HASH_MISMATCH = "PERMIT_PARENT_HASH_MISMATCH"
    DUPLICATE_ORDINAL = "DUPLICATE_ORDINAL"
    RESERVATION_BACKEND_INVALID = "RESERVATION_BACKEND_INVALID"

    RESERVATION_NOT_ATOMIC = "RESERVATION_NOT_ATOMIC"
    RELEASE_WITHOUT_PROOF = "RELEASE_WITHOUT_PROOF"
    UNKNOWN_START_MUST_HOLD = "UNKNOWN_START_MUST_HOLD"
    STALE_FENCE = "STALE_FENCE"
    ALLOWANCE_NOT_CONSERVED = "ALLOWANCE_NOT_CONSERVED"
    APPEND_ONLY_VIOLATION = "APPEND_ONLY_VIOLATION"

    # CompletionArtifactStore
    STORE_SYMLINK_REJECTED = "STORE_SYMLINK_REJECTED"
    STORE_BOUNDARY_ESCAPED = "STORE_BOUNDARY_ESCAPED"
    STORE_FALLBACK_REJECTED = "STORE_FALLBACK_REJECTED"
    STORE_HASH_MISMATCH = "STORE_HASH_MISMATCH"
    STORE_OVERWRITE_CONFLICT = "STORE_OVERWRITE_CONFLICT"
    STORE_VOLUME_ROOT_INVALID = "STORE_VOLUME_ROOT_INVALID"

    # WP-DB1L — 逻辑站点只读能力报告
    SITE_DATABASE_NAME_MISMATCH = "SITE_DATABASE_NAME_MISMATCH"
    SITE_DEFAULT_DATABASE_REJECTED = "SITE_DEFAULT_DATABASE_REJECTED"
    SITE_FINGERPRINT_MISMATCH = "SITE_FINGERPRINT_MISMATCH"
    SITE_CURRENT_DATABASE_MISMATCH = "SITE_CURRENT_DATABASE_MISMATCH"
    SITE_ENDPOINT_FINGERPRINT_MISMATCH = "SITE_ENDPOINT_FINGERPRINT_MISMATCH"
    SITE_PRINCIPAL_FINGERPRINT_MISMATCH = "SITE_PRINCIPAL_FINGERPRINT_MISMATCH"
    SITE_DRIVER_FINGERPRINT_MISMATCH = "SITE_DRIVER_FINGERPRINT_MISMATCH"
    SITE_SERVER_FINGERPRINT_MISMATCH = "SITE_SERVER_FINGERPRINT_MISMATCH"
    SITE_READONLY_PERMISSION_VIOLATION = "SITE_READONLY_PERMISSION_VIOLATION"
    CATALOG_MISSING = "CATALOG_MISSING"
    CATALOG_DRIFT = "CATALOG_DRIFT"
    CATALOG_COLLECTION_NOT_VERSIONED = "CATALOG_COLLECTION_NOT_VERSIONED"
    CATALOG_MATH_SYSTEM_COLLECTION_REUSE = "CATALOG_MATH_SYSTEM_COLLECTION_REUSE"
    CATALOG_EXTRA_SEVEN_COLLECTION = "CATALOG_EXTRA_SEVEN_COLLECTION"
    CATALOG_MISSING_SEVEN_COLLECTION = "CATALOG_MISSING_SEVEN_COLLECTION"
    DB1L_WRITE_DETECTED = "DB1L_WRITE_DETECTED"
    DB1L_CONNECTION_FAILURE = "DB1L_CONNECTION_FAILURE"
    DB1L_ZERO_WRITE_EVIDENCE_MISSING = "DB1L_ZERO_WRITE_EVIDENCE_MISSING"

    # WP-VLT0 Vault access chain
    VAULT_DENY_BY_DEFAULT_FALSE = "VAULT_DENY_BY_DEFAULT_FALSE"
    VAULT_RAW_PATH_DISCLOSED = "VAULT_RAW_PATH_DISCLOSED"
    VAULT_READ_RAW_OBJECT_REJECTED = "VAULT_READ_RAW_OBJECT_REJECTED"
    VAULT_CAPABILITY_HASH_MISMATCH = "VAULT_CAPABILITY_HASH_MISMATCH"
    VAULT_CAPABILITY_REVOKED = "VAULT_CAPABILITY_REVOKED"
    VAULT_CAPABILITY_EXPIRED = "VAULT_CAPABILITY_EXPIRED"
    VAULT_CAPABILITY_NOT_YET_VALID = "VAULT_CAPABILITY_NOT_YET_VALID"
    VAULT_NONCE_REPLAY = "VAULT_NONCE_REPLAY"
    VAULT_PRINCIPAL_MISMATCH = "VAULT_PRINCIPAL_MISMATCH"
    VAULT_OPERATION_MISMATCH = "VAULT_OPERATION_MISMATCH"
    VAULT_OBJECT_HASH_MISMATCH = "VAULT_OBJECT_HASH_MISMATCH"
    VAULT_VIEW_HASH_MISMATCH = "VAULT_VIEW_HASH_MISMATCH"
    VAULT_SINK_MISMATCH = "VAULT_SINK_MISMATCH"
    VAULT_REVOCATION_UNKNOWN = "VAULT_REVOCATION_UNKNOWN"
    VAULT_ACCESS_DENIED = "VAULT_ACCESS_DENIED"

    # WP-VLT0 View derivation
    VIEW_SOURCE_HASH_MISMATCH = "VIEW_SOURCE_HASH_MISMATCH"
    VIEW_RULE_HASH_MISMATCH = "VIEW_RULE_HASH_MISMATCH"
    VIEW_DERIVED_HASH_MISMATCH = "VIEW_DERIVED_HASH_MISMATCH"
    VIEW_SINK_RECEIPT_MISSING = "VIEW_SINK_RECEIPT_MISSING"
    VIEW_RAW_LOCATOR_EXPOSED = "VIEW_RAW_LOCATOR_EXPOSED"
    VIEW_CAPABILITY_TOKEN_EXPOSED = "VIEW_CAPABILITY_TOKEN_EXPOSED"
    VIEW_DELIVERY_MODE_INVALID = "VIEW_DELIVERY_MODE_INVALID"

    # WP-VLT0 Access event ledger
    ACCESS_LEDGER_SEQUENCE_CONFLICT = "ACCESS_LEDGER_SEQUENCE_CONFLICT"
    ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH = "ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH"
    ACCESS_LEDGER_TAMPERED = "ACCESS_LEDGER_TAMPERED"
    ACCESS_LEDGER_APPEND_ONLY_VIOLATION = "ACCESS_LEDGER_APPEND_ONLY_VIOLATION"
    ACCESS_EVENT_HASH_MISMATCH = "ACCESS_EVENT_HASH_MISMATCH"

    # WP-VLT0 Artifact seal protocol
    SEAL_LIVE_WRITER_STILL_ACTIVE = "SEAL_LIVE_WRITER_STILL_ACTIVE"
    SEAL_PARTIAL_INCOMPLETE = "SEAL_PARTIAL_INCOMPLETE"
    SEAL_ALREADY_SEALED = "SEAL_ALREADY_SEALED"
    SEAL_MANIFEST_HASH_MISMATCH = "SEAL_MANIFEST_HASH_MISMATCH"
    SEAL_COMMIT_INTENT_MISSING = "SEAL_COMMIT_INTENT_MISSING"
    SEAL_FENCE_STALE = "SEAL_FENCE_STALE"

    # WP-VLT0 CAS/DB reconcile
    RECONCILE_LIVE_WRITER_ACTIVE = "RECONCILE_LIVE_WRITER_ACTIVE"
    RECONCILE_PARTIAL_WRITER_DEAD = "RECONCILE_PARTIAL_WRITER_DEAD"
    RECONCILE_SEALED_DB_UNCOMMITTED = "RECONCILE_SEALED_DB_UNCOMMITTED"
    RECONCILE_DB_COMMITTED_ARTIFACT_MISSING = "RECONCILE_DB_COMMITTED_ARTIFACT_MISSING"
    RECONCILE_HASH_MISMATCH = "RECONCILE_HASH_MISMATCH"
    RECONCILE_CONFLICT = "RECONCILE_CONFLICT"
    RECONCILE_MISSING = "RECONCILE_MISSING"

    # WP-VLT0 CAS core reuse enforcement
    VAULT_SECOND_STORE_REJECTED = "VAULT_SECOND_STORE_REJECTED"

    # WP-IN1 CandidateManifest / Exporter — 只读 intake
    IN1_PRODUCTION_WRITE_REJECTED = "IN1_PRODUCTION_WRITE_REJECTED"
    IN1_PRODUCER_SCHEMA_NOT_FROZEN = "IN1_PRODUCER_SCHEMA_NOT_FROZEN"
    IN1_ROOT_HASH_MISMATCH = "IN1_ROOT_HASH_MISMATCH"
    IN1_EXPORT_MANIFEST_HASH_MISMATCH = "IN1_EXPORT_MANIFEST_HASH_MISMATCH"
    IN1_ATTEMPT_REF_HASH_MISMATCH = "IN1_ATTEMPT_REF_HASH_MISMATCH"
    IN1_MISSING_ARTIFACT = "IN1_MISSING_ARTIFACT"
    IN1_SOURCE_ROOT_DRIFT = "IN1_SOURCE_ROOT_DRIFT"
    IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT = "IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT"
    IN1_MUTABLE_REFERENCE_REJECTED = "IN1_MUTABLE_REFERENCE_REJECTED"
    IN1_PRODUCER_BUNDLE_INVALID = "IN1_PRODUCER_BUNDLE_INVALID"

    # 通用
    OBJECT_HASH_MISMATCH = "OBJECT_HASH_MISMATCH"
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"


class VerificationError(Exception):
    """验证器返回的结构化错误。

    验证器不抛异常——它们返回 VerificationResult。
    本异常仅用于内部断言或 CLI 层转换。
    """

    def __init__(self, code: VerificationErrorCode, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}" if detail else code.value)


# 完成合同到期望 schema_id 的映射
COMPLETION_CONTRACT_TO_SCHEMA_ID: dict[str, str] = {
    "DOC_BOOTSTRAP_RECORD": "seven/docs/doc-bootstrap-completion-record",
    "IMPLEMENTATION_BUNDLE": "seven/implementation-completion-bundle",
    "AUDIT_RECORD": "seven/audit-record",
}

# 实施者允许的完成合同
IMPLEMENTER_CONTRACTS: frozenset[str] = frozenset(
    {"DOC_BOOTSTRAP_RECORD", "IMPLEMENTATION_BUNDLE"}
)

# 审计者允许的完成合同
AUDITOR_CONTRACTS: frozenset[str] = frozenset({"AUDIT_RECORD"})

# 实施者不能写的状态
IMPLEMENTER_FORBIDDEN_STATES: frozenset[str] = frozenset(
    {"AUDITED_PASS", "AUDITED_PARTIAL", "AUDITED_FAIL"}
)

# 合法的工作包状态全集
VALID_STATES: frozenset[str] = frozenset(
    {
        "NOT_STARTED",
        "READY",
        "IN_PROGRESS",
        "IMPLEMENTED_PENDING_EVIDENCE",
        "READY_FOR_AUDIT",
        "AUDITED_PASS",
        "AUDITED_PARTIAL",
        "AUDITED_FAIL",
        "BLOCKED",
    }
)

# 签名算法注册表 v1
SIGNATURE_ALGORITHM_V1: str = "Ed25519"

# 预留后端枚举
RESERVATION_BACKENDS: frozenset[str] = frozenset(
    {
        "DB_V2_OR_EQUIVALENT_TRANSACTIONAL_LEDGER",
        "SCHEMA_BOOTSTRAP_D_VOLUME_LEDGER",
        "SIDE_EFFECT_FREE_REFERENCE",  # GV0 自身的 side-effect-free 参考后端
    }
)

# 授权消费状态枚举
CONSUMPTION_STATUSES: frozenset[str] = frozenset(
    {"RESERVED", "CONSUMED", "RELEASED_UNUSED", "UNKNOWN_START_HELD", "QUARANTINED"}
)

# 授权模式枚举
AUTHORIZATION_MODES: frozenset[str] = frozenset(
    {"AUDITED_ACTIVATION", "UNAUDITED_AUTHORIZED_CANARY", "TRUST_ROOT_OR_SCHEMA_BOOTSTRAP"}
)

# 额度字段全集（用于守恒检查）
ALLOWANCE_FIELDS: tuple[str, ...] = (
    "invocations",
    "solver_launches",
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "human_gate_commits",
    "active_release_changes",
    "tokens",
    "cost_microunits",
)

# ─── WP-VLT0 Vault 常量 ────────────────────────────────────────────────

# Vault 敏感度级别（有序，从低到高）
SENSITIVITY_LEVELS: tuple[str, ...] = (
    "PUBLIC",
    "RESTRICTED",
    "SOLUTION_BEARING",
    "HOLDOUT_BEARING",
)

# Vault 允许的操作（READ_RAW_OBJECT 不在此列表中）
VAULT_OPERATIONS: frozenset[str] = frozenset(
    {"READ_DERIVED_VIEW", "DERIVE_VIEW", "WRITE_RESTRICTED_OBJECT", "SEAL_RESTRICTED_OBJECT"}
)

# 被拒绝的操作
FORBIDDEN_OPERATIONS: frozenset[str] = frozenset(
    {"READ_RAW_OBJECT"}
)

# Vault principal 类型
VAULT_PRINCIPAL_TYPES: frozenset[str] = frozenset(
    {"MODEL_ROLE", "TARGET_SOLVER", "HUMAN", "SERVICE", "AUDITOR"}
)

# AccessDecision 结果
ACCESS_DECISIONS: frozenset[str] = frozenset({"ALLOW", "DENY"})

# AccessEvent 结果
ACCESS_EVENT_RESULTS: frozenset[str] = frozenset(
    {"ACCESS_GRANTED", "ACCESS_DENIED", "DERIVATION_FAILED", "ACCESS_REVOKED", "ACCESS_QUARANTINED"}
)

# AccessDecision reason codes
ACCESS_REASON_CODES: frozenset[str] = frozenset(
    {
        "POLICY_ALLOW",
        "CAPABILITY_INVALID",
        "ISSUER_UNTRUSTED",
        "OUTSIDE_TIME_WINDOW",
        "PRINCIPAL_MISMATCH",
        "OPERATION_MISMATCH",
        "OBJECT_HASH_MISMATCH",
        "VIEW_HASH_MISMATCH",
        "SINK_MISMATCH",
        "NONCE_REPLAY",
        "REVOKED",
        "REVOCATION_UNKNOWN",
        "POLICY_DENY",
    }
)

# Check result 枚举
CHECK_RESULTS: frozenset[str] = frozenset({"PASS", "FAIL", "UNKNOWN"})

# 撤销状态枚举
REVOCATION_STATUSES: frozenset[str] = frozenset(
    {"ACTIVE", "REVOKED", "EXPIRED", "UNKNOWN"}
)

# Sink kind 枚举
SINK_KINDS: frozenset[str] = frozenset(
    {"EPHEMERAL_MODEL_INPUT", "RESTRICTED_VAULT", "RESTRICTED_CAS", "AUDIT_ONLY"}
)

# Artifact seal 状态
SEAL_STATES: frozenset[str] = frozenset(
    {"LIVE", "PARTIAL", "SEALED", "MISSING", "CONFLICT"}
)

# Reconcile 状态
RECONCILE_STATES: frozenset[str] = frozenset(
    {
        "LIVE_WRITER_ACTIVE",
        "PARTIAL_WRITER_DEAD",
        "SEALED_DB_UNCOMMITTED",
        "DB_COMMITTED_ARTIFACT_MISSING",
        "SEALED_AND_COMMITTED",
        "MISSING",
        "CONFLICT",
    }
)
