"""GV0 固定错误码。

所有验证器返回结构化错误，不 TypeError 崩溃或跳过检查。
错误码是稳定枚举，下游消费者和审计者按码匹配，不按文本匹配。
"""

from __future__ import annotations

from enum import Enum


class VerificationErrorCode(str, Enum):
    """CompletionContractVerifier 和 SecurityContractVerifier 的固定错误码。"""

    # CompletionContractVerifier — owner / contract / schema / actor
    COMPLETION_CONTRACT_MISMATCH = "COMPLETION_CONTRACT_MISMATCH"
    ACTOR_NOT_AUTHORIZED = "ACTOR_NOT_AUTHORIZED"
    UNKNOWN_WORK_PACKAGE = "UNKNOWN_WORK_PACKAGE"
    SCHEMA_ID_MISMATCH = "SCHEMA_ID_MISMATCH"
    DAG_HASH_MISMATCH = "DAG_HASH_MISMATCH"
    DAG_LOAD_FAILED = "DAG_LOAD_FAILED"
    STATE_COMMAND_REJECTED = "STATE_COMMAND_REJECTED"

    # SecurityContractVerifier — 签名 / 授权链 / 额度
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    SIGNATURE_ALGORITHM_INVALID = "SIGNATURE_ALGORITHM_INVALID"
    SIGNATURE_DOMAIN_INVALID = "SIGNATURE_DOMAIN_INVALID"
    TIME_WINDOW_INVALID = "TIME_WINDOW_INVALID"
    TIME_NOT_CANONICAL_UTC = "TIME_NOT_CANONICAL_UTC"

    EEA_MODE_BINDING_INVALID = "EEA_MODE_BINDING_INVALID"
    EEA_ZERO_BUDGET = "EEA_ZERO_BUDGET"
    ACTION_REGISTRY_MISMATCH = "ACTION_REGISTRY_MISMATCH"

    PERMIT_ESCALATES_PARENT = "PERMIT_ESCALATES_PARENT"
    PERMIT_PARENT_HASH_MISMATCH = "PERMIT_PARENT_HASH_MISMATCH"
    DUPLICATE_ORDINAL = "DUPLICATE_ORDINAL"
    RESERVATION_BACKEND_INVALID = "RESERVATION_BACKEND_INVALID"

    RESERVATION_NOT_ATOMIC = "RESERVATION_NOT_ATOMIC"
    RELEASE_WITHOUT_PROOF = "RELEASE_WITHOUT_PROOF"
    UNKNOWN_START_MUST_HOLD = "UNKNOWN_START_MUST_HOLD"
    STALE_FENCE = "STALE_FENCE"
    ALLOWANCE_NOT_CONSERVED = "ALLOWANCE_NOT_CONSERVED"
    APPEND_ONLY_VIOLATION = "APPEND_ONLY_VIOLATION"

    # CompletionArtifactStore
    STORE_SYMLINK_REJECTED = "STORE_SYMLINK_REJECTED"
    STORE_BOUNDARY_ESCAPED = "STORE_BOUNDARY_ESCAPED"
    STORE_FALLBACK_REJECTED = "STORE_FALLBACK_REJECTED"
    STORE_HASH_MISMATCH = "STORE_HASH_MISMATCH"
    STORE_OVERWRITE_CONFLICT = "STORE_OVERWRITE_CONFLICT"
    STORE_VOLUME_ROOT_INVALID = "STORE_VOLUME_ROOT_INVALID"

    # WP-DB1L — 逻辑站点只读能力报告
    SITE_DATABASE_NAME_MISMATCH = "SITE_DATABASE_NAME_MISMATCH"
    SITE_DEFAULT_DATABASE_REJECTED = "SITE_DEFAULT_DATABASE_REJECTED"
    SITE_FINGERPRINT_MISMATCH = "SITE_FINGERPRINT_MISMATCH"
    SITE_CURRENT_DATABASE_MISMATCH = "SITE_CURRENT_DATABASE_MISMATCH"
    SITE_ENDPOINT_FINGERPRINT_MISMATCH = "SITE_ENDPOINT_FINGERPRINT_MISMATCH"
    SITE_PRINCIPAL_FINGERPRINT_MISMATCH = "SITE_PRINCIPAL_FINGERPRINT_MISMATCH"
    SITE_DRIVER_FINGERPRINT_MISMATCH = "SITE_DRIVER_FINGERPRINT_MISMATCH"
    SITE_SERVER_FINGERPRINT_MISMATCH = "SITE_SERVER_FINGERPRINT_MISMATCH"
    SITE_READONLY_PERMISSION_VIOLATION = "SITE_READONLY_PERMISSION_VIOLATION"
    CATALOG_MISSING = "CATALOG_MISSING"
    CATALOG_DRIFT = "CATALOG_DRIFT"
    CATALOG_COLLECTION_NOT_VERSIONED = "CATALOG_COLLECTION_NOT_VERSIONED"
    CATALOG_MATH_SYSTEM_COLLECTION_REUSE = "CATALOG_MATH_SYSTEM_COLLECTION_REUSE"
    CATALOG_EXTRA_SEVEN_COLLECTION = "CATALOG_EXTRA_SEVEN_COLLECTION"
    CATALOG_MISSING_SEVEN_COLLECTION = "CATALOG_MISSING_SEVEN_COLLECTION"
    DB1L_WRITE_DETECTED = "DB1L_WRITE_DETECTED"
    DB1L_CONNECTION_FAILURE = "DB1L_CONNECTION_FAILURE"
    DB1L_ZERO_WRITE_EVIDENCE_MISSING = "DB1L_ZERO_WRITE_EVIDENCE_MISSING"

    # WP-VLT0 Vault access chain
    VAULT_DENY_BY_DEFAULT_FALSE = "VAULT_DENY_BY_DEFAULT_FALSE"
    VAULT_RAW_PATH_DISCLOSED = "VAULT_RAW_PATH_DISCLOSED"
    VAULT_READ_RAW_OBJECT_REJECTED = "VAULT_READ_RAW_OBJECT_REJECTED"
    VAULT_CAPABILITY_HASH_MISMATCH = "VAULT_CAPABILITY_HASH_MISMATCH"
    VAULT_CAPABILITY_REVOKED = "VAULT_CAPABILITY_REVOKED"
    VAULT_CAPABILITY_EXPIRED = "VAULT_CAPABILITY_EXPIRED"
    VAULT_CAPABILITY_NOT_YET_VALID = "VAULT_CAPABILITY_NOT_YET_VALID"
    VAULT_NONCE_REPLAY = "VAULT_NONCE_REPLAY"
    VAULT_PRINCIPAL_MISMATCH = "VAULT_PRINCIPAL_MISMATCH"
    VAULT_OPERATION_MISMATCH = "VAULT_OPERATION_MISMATCH"
    VAULT_OBJECT_HASH_MISMATCH = "VAULT_OBJECT_HASH_MISMATCH"
    VAULT_VIEW_HASH_MISMATCH = "VAULT_VIEW_HASH_MISMATCH"
    VAULT_SINK_MISMATCH = "VAULT_SINK_MISMATCH"
    VAULT_REVOCATION_UNKNOWN = "VAULT_REVOCATION_UNKNOWN"
    VAULT_ACCESS_DENIED = "VAULT_ACCESS_DENIED"

    # WP-VLT0 View derivation
    VIEW_SOURCE_HASH_MISMATCH = "VIEW_SOURCE_HASH_MISMATCH"
    VIEW_RULE_HASH_MISMATCH = "VIEW_RULE_HASH_MISMATCH"
    VIEW_DERIVED_HASH_MISMATCH = "VIEW_DERIVED_HASH_MISMATCH"
    VIEW_SINK_RECEIPT_MISSING = "VIEW_SINK_RECEIPT_MISSING"
    VIEW_RAW_LOCATOR_EXPOSED = "VIEW_RAW_LOCATOR_EXPOSED"
    VIEW_CAPABILITY_TOKEN_EXPOSED = "VIEW_CAPABILITY_TOKEN_EXPOSED"
    VIEW_DELIVERY_MODE_INVALID = "VIEW_DELIVERY_MODE_INVALID"

    # WP-VLT0 Access event ledger
    ACCESS_LEDGER_SEQUENCE_CONFLICT = "ACCESS_LEDGER_SEQUENCE_CONFLICT"
    ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH = "ACCESS_LEDGER_PREVIOUS_HASH_MISMATCH"
    ACCESS_LEDGER_TAMPERED = "ACCESS_LEDGER_TAMPERED"
    ACCESS_LEDGER_APPEND_ONLY_VIOLATION = "ACCESS_LEDGER_APPEND_ONLY_VIOLATION"
    ACCESS_EVENT_HASH_MISMATCH = "ACCESS_EVENT_HASH_MISMATCH"

    # WP-VLT0 Artifact seal protocol
    SEAL_LIVE_WRITER_STILL_ACTIVE = "SEAL_LIVE_WRITER_STILL_ACTIVE"
    SEAL_PARTIAL_INCOMPLETE = "SEAL_PARTIAL_INCOMPLETE"
    SEAL_ALREADY_SEALED = "SEAL_ALREADY_SEALED"
    SEAL_MANIFEST_HASH_MISMATCH = "SEAL_MANIFEST_HASH_MISMATCH"
    SEAL_COMMIT_INTENT_MISSING = "SEAL_COMMIT_INTENT_MISSING"
    SEAL_FENCE_STALE = "SEAL_FENCE_STALE"

    # WP-VLT0 CAS/DB reconcile
    RECONCILE_LIVE_WRITER_ACTIVE = "RECONCILE_LIVE_WRITER_ACTIVE"
    RECONCILE_PARTIAL_WRITER_DEAD = "RECONCILE_PARTIAL_WRITER_DEAD"
    RECONCILE_SEALED_DB_UNCOMMITTED = "RECONCILE_SEALED_DB_UNCOMMITTED"
    RECONCILE_DB_COMMITTED_ARTIFACT_MISSING = "RECONCILE_DB_COMMITTED_ARTIFACT_MISSING"
    RECONCILE_HASH_MISMATCH = "RECONCILE_HASH_MISMATCH"
    RECONCILE_CONFLICT = "RECONCILE_CONFLICT"
    RECONCILE_MISSING = "RECONCILE_MISSING"

    # WP-VLT0 CAS core reuse enforcement
    VAULT_SECOND_STORE_REJECTED = "VAULT_SECOND_STORE_REJECTED"

    # WP-IN1 CandidateManifest / Exporter — 只读 intake
    IN1_PRODUCTION_WRITE_REJECTED = "IN1_PRODUCTION_WRITE_REJECTED"
    IN1_PRODUCER_SCHEMA_NOT_FROZEN = "IN1_PRODUCER_SCHEMA_NOT_FROZEN"
    IN1_ROOT_HASH_MISMATCH = "IN1_ROOT_HASH_MISMATCH"
    IN1_EXPORT_MANIFEST_HASH_MISMATCH = "IN1_EXPORT_MANIFEST_HASH_MISMATCH"
    IN1_ATTEMPT_REF_HASH_MISMATCH = "IN1_ATTEMPT_REF_HASH_MISMATCH"
    IN1_MISSING_ARTIFACT = "IN1_MISSING_ARTIFACT"
    IN1_SOURCE_ROOT_DRIFT = "IN1_SOURCE_ROOT_DRIFT"
    IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT = "IN1_DUPLICATE_CANDIDATE_IN_ATTEMPT"
    IN1_MUTABLE_REFERENCE_REJECTED = "IN1_MUTABLE_REFERENCE_REJECTED"
    IN1_PRODUCER_BUNDLE_INVALID = "IN1_PRODUCER_BUNDLE_INVALID"

    # WP-HG0 HumanGate — actor / roster / gate type
    ACTOR_NOT_IN_ROSTER = "ACTOR_NOT_IN_ROSTER"
    ACTOR_INACTIVE = "ACTOR_INACTIVE"
    ACTOR_TYPE_INVALID = "ACTOR_TYPE_INVALID"
    ACTOR_ROLE_MISSING = "ACTOR_ROLE_MISSING"
    GATE_TYPE_UNKNOWN = "GATE_TYPE_UNKNOWN"
    GATE_REQUIRED_ROLE_MISSING = "GATE_REQUIRED_ROLE_MISSING"
    GATE_REQUIRED_SIGNATURES_NOT_MET = "GATE_REQUIRED_SIGNATURES_NOT_MET"
    GATE_SELF_APPROVAL_REJECTED = "GATE_SELF_APPROVAL_REJECTED"
    GATE_DUTY_CONFLICT = "GATE_DUTY_CONFLICT"
    GATE_DECISION_UNSIGNED = "GATE_DECISION_UNSIGNED"
    GATE_DECISION_HASH_MISMATCH = "GATE_DECISION_HASH_MISMATCH"
    GATE_PAYLOAD_HASH_MISMATCH = "GATE_PAYLOAD_HASH_MISMATCH"
    GATE_REPLAY_DETECTED = "GATE_REPLAY_DETECTED"
    GATE_NONCE_INVALID = "GATE_NONCE_INVALID"

    # WP-HG0 HumanGate — key lifecycle
    KEY_NOT_REGISTERED = "KEY_NOT_REGISTERED"
    KEY_REVOKED = "KEY_REVOKED"
    KEY_EXPIRED = "KEY_EXPIRED"
    KEY_NOT_YET_VALID = "KEY_NOT_YET_VALID"
    KEY_ACTOR_MISMATCH = "KEY_ACTOR_MISMATCH"
    KEY_ROLE_NOT_ELIGIBLE = "KEY_ROLE_NOT_ELIGIBLE"

    # WP-HG0 HumanGate — GV0 consumption
    HG0_COMPLETION_CONTRACT_NOT_CONSUMED = "HG0_COMPLETION_CONTRACT_NOT_CONSUMED"
    HG0_STATE_COMMAND_REJECTED = "HG0_STATE_COMMAND_REJECTED"

    # WP-CW0 ModelRolePort / attempt / receipt / reconcile
    CW0_UNKNOWN_ROLE = "CW0_UNKNOWN_ROLE"
    CW0_ROLE_NOT_FROZEN = "CW0_ROLE_NOT_FROZEN"
    CW0_REGISTRY_HASH_MISMATCH = "CW0_REGISTRY_HASH_MISMATCH"
    CW0_ROLE_MISSING_REQUIRED_PROFILE = "CW0_ROLE_MISSING_REQUIRED_PROFILE"
    CW0_ROLE_MISSING_VIEW_POLICY = "CW0_ROLE_MISSING_VIEW_POLICY"
    CW0_ROLE_TOOL_POLICY_ALLOWS_TOOLS = "CW0_ROLE_TOOL_POLICY_ALLOWS_TOOLS"
    CW0_CONTRACT_HASH_MISMATCH = "CW0_CONTRACT_HASH_MISMATCH"
    CW0_CONTRACT_ROLE_MISMATCH = "CW0_CONTRACT_ROLE_MISMATCH"
    CW0_CONTRACT_PROFILE_MISMATCH = "CW0_CONTRACT_PROFILE_MISMATCH"
    CW0_CONTRACT_VIEW_POLICY_MISMATCH = "CW0_CONTRACT_VIEW_POLICY_MISMATCH"
    CW0_CONTRACT_TOOL_POLICY_MISMATCH = "CW0_CONTRACT_TOOL_POLICY_MISMATCH"
    CW0_CONTRACT_CAPABILITY_MISMATCH = "CW0_CONTRACT_CAPABILITY_MISMATCH"
    CW0_CONTRACT_ADAPTER_MISMATCH = "CW0_CONTRACT_ADAPTER_MISMATCH"

    # Attempt lifecycle
    ATTEMPT_UNKNOWN_START = "ATTEMPT_UNKNOWN_START"
    ATTEMPT_STALE_FENCE = "ATTEMPT_STALE_FENCE"
    ATTEMPT_SENSITIVE_SINK = "ATTEMPT_SENSITIVE_SINK"
    ATTEMPT_ILLEGAL_STATE_TRANSITION = "ATTEMPT_ILLEGAL_STATE_TRANSITION"
    ATTEMPT_NOT_ACCEPTED = "ATTEMPT_NOT_ACCEPTED"
    ATTEMPT_ALREADY_TERMINATED = "ATTEMPT_ALREADY_TERMINATED"
    ATTEMPT_NOT_STARTED = "ATTEMPT_NOT_STARTED"
    ATTEMPT_CANCELLED = "ATTEMPT_CANCELLED"
    ATTEMPT_TIMEOUT = "ATTEMPT_TIMEOUT"
    ATTEMPT_FENCE_TOKEN_MISMATCH = "ATTEMPT_FENCE_TOKEN_MISMATCH"
    ATTEMPT_RECEIPT_HASH_MISMATCH = "ATTEMPT_RECEIPT_HASH_MISMATCH"
    ATTEMPT_OUTPUT_SCHEMA_INVALID = "ATTEMPT_OUTPUT_SCHEMA_INVALID"
    ATTEMPT_DETERMINISM_VIOLATION = "ATTEMPT_DETERMINISM_VIOLATION"

    # Reconcile
    RECONCILE_UNKNOWN_START = "RECONCILE_UNKNOWN_START"
    RECONCILE_STALE_FENCE = "RECONCILE_STALE_FENCE"
    RECONCILE_SENSITIVE_SINK = "RECONCILE_SENSITIVE_SINK"
    RECONCILE_ILLEGAL_STATE = "RECONCILE_ILLEGAL_STATE"

    # WP-DB1I — Schema bootstrap / fenced apply / D-volume ledger
    DB1I_MIGRATION_SPEC_HASH_DRIFT = "DB1I_MIGRATION_SPEC_HASH_DRIFT"
    DB1I_PLAN_HASH_DRIFT = "DB1I_PLAN_HASH_DRIFT"
    DB1I_SITE_FINGERPRINT_MISMATCH = "DB1I_SITE_FINGERPRINT_MISMATCH"
    DB1I_DB1L_REPORT_MISSING = "DB1I_DB1L_REPORT_MISSING"
    DB1I_HUMAN_GATE_DECISION_MISSING = "DB1I_HUMAN_GATE_DECISION_MISSING"
    DB1I_HUMAN_GATE_DECISION_REJECTED = "DB1I_HUMAN_GATE_DECISION_REJECTED"
    DB1I_FENCE_MISSING = "DB1I_FENCE_MISSING"
    DB1I_FENCE_STALE = "DB1I_FENCE_STALE"
    DB1I_FENCE_DUPLICATE = "DB1I_FENCE_DUPLICATE"
    DB1I_DUPLICATE_APPLY = "DB1I_DUPLICATE_APPLY"
    DB1I_APPLY_WITHOUT_FENCE = "DB1I_APPLY_WITHOUT_FENCE"
    DB1I_UNKNOWN_OUTCOME = "DB1I_UNKNOWN_OUTCOME"
    DB1I_RESUME_CATALOG_MISMATCH = "DB1I_RESUME_CATALOG_MISMATCH"
    DB1I_LEDGER_TAMPERED = "DB1I_LEDGER_TAMPERED"
    DB1I_LEDGER_PREVIOUS_HASH_MISMATCH = "DB1I_LEDGER_PREVIOUS_HASH_MISMATCH"
    DB1I_IMPORT_ANCHOR_HASH_MISMATCH = "DB1I_IMPORT_ANCHOR_HASH_MISMATCH"
    DB1I_BOOTSTRAP_RECEIPT_HASH_MISMATCH = "DB1I_BOOTSTRAP_RECEIPT_HASH_MISMATCH"
    DB1I_SCHEMA_STATE_REPORT_INVALID = "DB1I_SCHEMA_STATE_REPORT_INVALID"
    DB1I_RUNTIME_CAPABILITY_NOT_ALLOWED = "DB1I_RUNTIME_CAPABILITY_NOT_ALLOWED"
    DB1I_RECONCILE_CAPABILITY_NOT_ALLOWED = "DB1I_RECONCILE_CAPABILITY_NOT_ALLOWED"
    DB1I_PERMIT_MISMATCH = "DB1I_PERMIT_MISMATCH"
    DB1I_ACTION_OUT_OF_RANGE = "DB1I_ACTION_OUT_OF_RANGE"

    # WP-CW-D1 DevinCliModelRoleAdapter — profile / parser / capability
    CWD1_MODEL_UID_MISMATCH = "CWD1_MODEL_UID_MISMATCH"
    CWD1_EFFORT_MISMATCH = "CWD1_EFFORT_MISMATCH"
    CWD1_EFFORT_ENCODING_INVALID = "CWD1_EFFORT_ENCODING_INVALID"
    CWD1_PROFILE_DRIFT = "CWD1_PROFILE_DRIFT"
    CWD1_ATIF_PARSE_FAILED = "CWD1_ATIF_PARSE_FAILED"
    CWD1_ATIF_GENERATION_MODEL_MISSING = "CWD1_ATIF_GENERATION_MODEL_MISSING"
    CWD1_ATIF_TOOL_EVENT_DETECTED = "CWD1_ATIF_TOOL_EVENT_DETECTED"
    CWD1_CATALOG_SNAPSHOT_MISSING = "CWD1_CATALOG_SNAPSHOT_MISSING"
    CWD1_REASONING_MODE_UNOBSERVABLE = "CWD1_REASONING_MODE_UNOBSERVABLE"

    # WP-CW-C1 CodexExecModelRoleAdapter — profile / parser / capability
    CWC1_MODEL_MISMATCH = "CWC1_MODEL_MISMATCH"
    CWC1_EFFORT_MISMATCH = "CWC1_EFFORT_MISMATCH"
    CWC1_MODE_MISMATCH = "CWC1_MODE_MISMATCH"
    CWC1_ORCHESTRATION_MISMATCH = "CWC1_ORCHESTRATION_MISMATCH"
    CWC1_PROFILE_DRIFT = "CWC1_PROFILE_DRIFT"
    CWC1_JSONL_PARSE_FAILED = "CWC1_JSONL_PARSE_FAILED"
    CWC1_JSONL_EVENT_GAP = "CWC1_JSONL_EVENT_GAP"
    CWC1_JSONL_NO_TERMINAL = "CWC1_JSONL_NO_TERMINAL"
    CWC1_JSONL_TOOL_EVENT_DETECTED = "CWC1_JSONL_TOOL_EVENT_DETECTED"
    CWC1_CHILD_USAGE_MISSING = "CWC1_CHILD_USAGE_MISSING"
    CWC1_ARGUMENT_MAPPING_MISSING = "CWC1_ARGUMENT_MAPPING_MISSING"

    # Profile capability report — cross-adapter
    PROFILE_REQUESTED_EFFECTIVE_MISMATCH = "PROFILE_REQUESTED_EFFECTIVE_MISMATCH"
    PROFILE_UNOBSERVABLE_FIELD_NOT_DECLARED = "PROFILE_UNOBSERVABLE_FIELD_NOT_DECLARED"
    PROFILE_REQUIRED_FIELD_MISSING = "PROFILE_REQUIRED_FIELD_MISSING"
    PROFILE_ADAPTER_KIND_MISMATCH = "PROFILE_ADAPTER_KIND_MISMATCH"
    PROFILE_TOOL_POLICY_VIOLATION = "PROFILE_TOOL_POLICY_VIOLATION"
    PROFILE_VIEW_POLICY_VIOLATION = "PROFILE_VIEW_POLICY_VIOLATION"

    # Bypass tests — adapter must NOT use solver_harness / repo workspace / tool events
    BYPASS_SOLVER_HARNESS_USED = "BYPASS_SOLVER_HARNESS_USED"
    BYPASS_REPO_WORKSPACE_USED = "BYPASS_REPO_WORKSPACE_USED"
    BYPASS_TOOL_EVENT_DETECTED = "BYPASS_TOOL_EVENT_DETECTED"

    # 通用
    OBJECT_HASH_MISMATCH = "OBJECT_HASH_MISMATCH"
    REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"


class VerificationError(Exception):
    """验证器返回的结构化错误。

    验证器不抛异常——它们返回 VerificationResult。
    本异常仅用于内部断言或 CLI 层转换。
    """

    def __init__(self, code: VerificationErrorCode, detail: str = "") -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}" if detail else code.value)


# 完成合同到期望 schema_id 的映射
COMPLETION_CONTRACT_TO_SCHEMA_ID: dict[str, str] = {
    "DOC_BOOTSTRAP_RECORD": "seven/docs/doc-bootstrap-completion-record",
    "IMPLEMENTATION_BUNDLE": "seven/implementation-completion-bundle",
    "AUDIT_RECORD": "seven/audit-record",
}

# 实施者允许的完成合同
IMPLEMENTER_CONTRACTS: frozenset[str] = frozenset(
    {"DOC_BOOTSTRAP_RECORD", "IMPLEMENTATION_BUNDLE"}
)

# 审计者允许的完成合同
AUDITOR_CONTRACTS: frozenset[str] = frozenset({"AUDIT_RECORD"})

# 实施者不能写的状态
IMPLEMENTER_FORBIDDEN_STATES: frozenset[str] = frozenset(
    {"AUDITED_PASS", "AUDITED_PARTIAL", "AUDITED_FAIL"}
)

# 合法的工作包状态全集
VALID_STATES: frozenset[str] = frozenset(
    {
        "NOT_STARTED",
        "READY",
        "IN_PROGRESS",
        "IMPLEMENTED_PENDING_EVIDENCE",
        "READY_FOR_AUDIT",
        "AUDITED_PASS",
        "AUDITED_PARTIAL",
        "AUDITED_FAIL",
        "BLOCKED",
    }
)

# 签名算法注册表 v1
SIGNATURE_ALGORITHM_V1: str = "Ed25519"

# 预留后端枚举
RESERVATION_BACKENDS: frozenset[str] = frozenset(
    {
        "DB_V2_OR_EQUIVALENT_TRANSACTIONAL_LEDGER",
        "SCHEMA_BOOTSTRAP_D_VOLUME_LEDGER",
        "SIDE_EFFECT_FREE_REFERENCE",  # GV0 自身的 side-effect-free 参考后端
    }
)

# 授权消费状态枚举
CONSUMPTION_STATUSES: frozenset[str] = frozenset(
    {"RESERVED", "CONSUMED", "RELEASED_UNUSED", "UNKNOWN_START_HELD", "QUARANTINED"}
)

# 授权模式枚举
AUTHORIZATION_MODES: frozenset[str] = frozenset(
    {"AUDITED_ACTIVATION", "UNAUDITED_AUTHORIZED_CANARY", "TRUST_ROOT_OR_SCHEMA_BOOTSTRAP"}
)

# 额度字段全集（用于守恒检查）
ALLOWANCE_FIELDS: tuple[str, ...] = (
    "invocations",
    "solver_launches",
    "database_writes",
    "redis_writes",
    "d_volume_writes",
    "human_gate_commits",
    "active_release_changes",
    "tokens",
    "cost_microunits",
)

# ─── WP-VLT0 Vault 常量 ────────────────────────────────────────────────

# Vault 敏感度级别（有序，从低到高）
SENSITIVITY_LEVELS: tuple[str, ...] = (
    "PUBLIC",
    "RESTRICTED",
    "SOLUTION_BEARING",
    "HOLDOUT_BEARING",
)

# Vault 允许的操作（READ_RAW_OBJECT 不在此列表中）
VAULT_OPERATIONS: frozenset[str] = frozenset(
    {"READ_DERIVED_VIEW", "DERIVE_VIEW", "WRITE_RESTRICTED_OBJECT", "SEAL_RESTRICTED_OBJECT"}
)

# 被拒绝的操作
FORBIDDEN_OPERATIONS: frozenset[str] = frozenset(
    {"READ_RAW_OBJECT"}
)

# Vault principal 类型
VAULT_PRINCIPAL_TYPES: frozenset[str] = frozenset(
    {"MODEL_ROLE", "TARGET_SOLVER", "HUMAN", "SERVICE", "AUDITOR"}
)

# AccessDecision 结果
ACCESS_DECISIONS: frozenset[str] = frozenset({"ALLOW", "DENY"})

# AccessEvent 结果
ACCESS_EVENT_RESULTS: frozenset[str] = frozenset(
    {"ACCESS_GRANTED", "ACCESS_DENIED", "DERIVATION_FAILED", "ACCESS_REVOKED", "ACCESS_QUARANTINED"}
)

# AccessDecision reason codes
ACCESS_REASON_CODES: frozenset[str] = frozenset(
    {
        "POLICY_ALLOW",
        "CAPABILITY_INVALID",
        "ISSUER_UNTRUSTED",
        "OUTSIDE_TIME_WINDOW",
        "PRINCIPAL_MISMATCH",
        "OPERATION_MISMATCH",
        "OBJECT_HASH_MISMATCH",
        "VIEW_HASH_MISMATCH",
        "SINK_MISMATCH",
        "NONCE_REPLAY",
        "REVOKED",
        "REVOCATION_UNKNOWN",
        "POLICY_DENY",
    }
)

# Check result 枚举
CHECK_RESULTS: frozenset[str] = frozenset({"PASS", "FAIL", "UNKNOWN"})

# 撤销状态枚举
REVOCATION_STATUSES: frozenset[str] = frozenset(
    {"ACTIVE", "REVOKED", "EXPIRED", "UNKNOWN"}
)

# Sink kind 枚举
SINK_KINDS: frozenset[str] = frozenset(
    {"EPHEMERAL_MODEL_INPUT", "RESTRICTED_VAULT", "RESTRICTED_CAS", "AUDIT_ONLY"}
)

# Artifact seal 状态
SEAL_STATES: frozenset[str] = frozenset(
    {"LIVE", "PARTIAL", "SEALED", "MISSING", "CONFLICT"}
)

# Reconcile 状态
RECONCILE_STATES: frozenset[str] = frozenset(
    {
        "LIVE_WRITER_ACTIVE",
        "PARTIAL_WRITER_DEAD",
        "SEALED_DB_UNCOMMITTED",
        "DB_COMMITTED_ARTIFACT_MISSING",
        "SEALED_AND_COMMITTED",
        "MISSING",
        "CONFLICT",
    }
)

# ─── WP-HG0 HumanGate 常量 ──────────────────────────────────────────────

# Actor 类型（谁可以参与 HumanGate）
ACTOR_TYPES: frozenset[str] = frozenset(
    {"HUMAN", "MODEL_ROLE", "SERVICE"}
)

# HumanGate 角色枚举
HUMAN_GATE_ROLES: frozenset[str] = frozenset(
    {
        "QUESTION_ARCHITECT",
        "ADVERSARIAL_EDITOR",
        "MATH_VERIFIER",
        "PROCESS_AUDITOR",
        "PROOF_JUDGE",
        "LEAKAGE_AUDITOR",
        "SELECTOR_RENDERER",
        "SITE_OWNER",
        "PROVISIONING_ACTOR",
    }
)

# Gate decision 结果枚举
GATE_DECISIONS: frozenset[str] = frozenset(
    {"APPROVE", "REJECT", "REQUEST_CHANGES", "QUARANTINE"}
)

# Gate verification status 枚举
GATE_VERIFICATION_STATUSES: frozenset[str] = frozenset(
    {"HUMAN_PENDING", "VERIFIED", "BLOCKED", "QUARANTINED"}
)

# Key lifecycle 状态枚举
KEY_STATUSES: frozenset[str] = frozenset(
    {"ACTIVE", "REVOKED", "EXPIRED", "PENDING"}
)

# HumanGate 签名 domain separator（含实际 NUL byte）
HUMAN_GATE_SIGNATURE_DOMAIN: str = "seven-human-gate-decision/v1\0"

# HumanGate signed_bytes_hash algorithm
HUMAN_GATE_HASH_ALGORITHM: str = "sha256(RFC8785-JCS-object-with-decision_hash-null)"

# ─── WP-CW0 ModelRolePort 常量 ──────────────────────────────────────────

# Attempt 状态枚举（有序状态机）
ATTEMPT_STATES: frozenset[str] = frozenset(
    {
        "CREATED",
        "ACCEPTED",
        "STARTED",
        "COMPLETED",
        "TERMINATED",
        "CANCELLED",
        "TIMED_OUT",
        "UNKNOWN_START_QUARANTINED",
    }
)

# 合法状态转换
ATTEMPT_TRANSITIONS: dict[str, frozenset[str]] = {
    "CREATED": frozenset({"ACCEPTED"}),
    "ACCEPTED": frozenset({"STARTED", "CANCELLED", "TIMED_OUT", "UNKNOWN_START_QUARANTINED"}),
    "STARTED": frozenset({"COMPLETED", "TERMINATED", "CANCELLED", "TIMED_OUT"}),
    "COMPLETED": frozenset(),  # 终态
    "TERMINATED": frozenset(),  # 终态
    "CANCELLED": frozenset(),  # 终态
    "TIMED_OUT": frozenset(),  # 终态
    "UNKNOWN_START_QUARANTINED": frozenset({"TERMINATED", "CANCELLED"}),
}

# 终态集合
ATTEMPT_TERMINAL_STATES: frozenset[str] = frozenset(
    {"COMPLETED", "TERMINATED", "CANCELLED", "TIMED_OUT"}
)

# Adapter 类型枚举
MODEL_ROLE_ADAPTER_KINDS: frozenset[str] = frozenset(
    {"FAKE", "DEVIN_CLI", "CODEX_EXEC", "OPENAI_RESPONSES"}
)

# Tool policy 枚举
TOOL_POLICY_KINDS: frozenset[str] = frozenset(
    {"NO_TOOLS", "READ_ONLY_TOOLS", "SANDBOXED_TOOLS"}
)

# View policy 枚举
VIEW_POLICY_KINDS: frozenset[str] = frozenset(
    {"PUBLIC_ONLY", "RESTRICTED_DERIVED", "SOLUTION_BEARING_DERIVED"}
)

# Output sink kind 枚举（attempt 输出目的地）
ATTEMPT_OUTPUT_SINK_KINDS: frozenset[str] = frozenset(
    {"EPHEMERAL_MODEL_OUTPUT", "RESTRICTED_VAULT", "AUDIT_ONLY"}
)

# Reconcile verdict 枚举
ATTEMPT_RECONCILE_VERDICTS: frozenset[str] = frozenset(
    {"CONSISTENT", "UNKNOWN_START", "STALE_FENCE", "SENSITIVE_SINK", "ILLEGAL_STATE"}
)

# RoleTypeRegistry 常量
ROLE_TYPE_REGISTRY_ID: str = "seven_model_role_types"
ROLE_TYPE_REGISTRY_SCHEMA_VERSION: str = "role_type_registry.v1"

# ─── WP-DB1I Schema bootstrap 常量 ──────────────────────────────────────

# Schema bootstrap ledger entry 类型（D 盘 append-only ledger）
SCHEMA_BOOTSTRAP_LEDGER_ENTRY_TYPES: frozenset[str] = frozenset(
    {
        "ACTION_INTENT",
        "ACTION_VERIFIED",
        "ACTION_FAILED",
        "UNKNOWN_OUTCOME",
        "FENCE_ACQUIRED",
        "FENCE_RELEASED",
    }
)

# Schema bootstrap action 状态
SCHEMA_BOOTSTRAP_ACTION_STATES: frozenset[str] = frozenset(
    {"PENDING", "INTENTED", "APPLIED", "VERIFIED", "FAILED", "UNKNOWN_OUTCOME"}
)

# Schema bootstrap fence 状态
SCHEMA_BOOTSTRAP_FENCE_STATES: frozenset[str] = frozenset(
    {"ACTIVE", "RELEASED", "EXPIRED", "SUPERSEDED"}
)

# DB1I 完成输出严格限定为这三类对象
DB1I_ALLOWED_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseSchemaStateReport",
        "SchemaBootstrapReceipt",
        "SchemaBootstrapImportAnchor",
    }
)

# DB1I 明确禁止输出的能力报告
DB1I_FORBIDDEN_OUTPUT_KINDS: frozenset[str] = frozenset(
    {
        "DatabaseRuntimeCapabilityReport",
        "ArtifactCommitReconcileCapabilityReport",
    }
)

# ─── WP-CW-D1 / WP-CW-C1 Adapter 常量 ──────────────────────────────────────

# Devin CLI 冻结 profile 字段
DEVIN_PROFILE_FIELDS: frozenset[str] = frozenset(
    {
        "carrier",
        "requested_cli_model_arg",
        "normalized_reasoning_effort",
        "effort_encoding",
        "reasoning_mode_request_semantics",
        "orchestration_request_semantics",
        "model_catalog_snapshot_ref_and_hash",
    }
)

# Devin CLI 冻结的 model UID（本机只读 catalog 观察）
DEVIN_FROZEN_MODEL_UID: str = "glm-5-2"
DEVIN_FROZEN_MODEL_DISPLAY: str = "GLM-5.2 High"
DEVIN_FROZEN_EFFORT: str = "high"
DEVIN_EFFORT_ENCODING: str = "model_uid"

# Codex CLI 冻结 profile 字段
CODEX_PROFILE_FIELDS: frozenset[str] = frozenset(
    {
        "carrier",
        "backend_kind",
        "requested_model",
        "model_alias_resolution_policy",
        "requested_reasoning_effort",
        "requested_reasoning_mode",
        "requested_orchestration_mode",
        "requested_service_tier",
        "sandbox_policy_ref_and_hash",
        "tool_policy_ref_and_hash",
        "network_policy_ref_and_hash",
        "output_schema_ref_and_hash",
        "cli_argument_mapping_ref_and_hash",
        "model_release_or_catalog_snapshot_ref_and_hash",
    }
)

# Codex CLI 冻结候选（NOT_TESTED，仅静态候选）
CODEX_FROZEN_MODEL: str = "gpt-5.6-sol"
CODEX_FROZEN_EFFORT: str = "xhigh"
CODEX_FROZEN_MODE: str = "standard"
CODEX_FROZEN_ORCHESTRATION: str = "single_agent"

# Profile capability report 中可声明为 UNOBSERVABLE 的字段
PROFILE_UNOBSERVABLE_FIELDS: frozenset[str] = frozenset(
    {
        "effective_reasoning_mode",
        "effective_orchestration_mode",
        "effective_effort",
    }
)

# Bypass test 名称枚举
BYPASS_TEST_NAMES: frozenset[str] = frozenset(
    {
        "direct_devin_bypass",
        "tool_event_test",
        "repo_workspace_test",
    }
)

# Bypass test 结果枚举
BYPASS_TEST_RESULTS: frozenset[str] = frozenset(
    {"PASS", "FAIL", "NOT_APPLICABLE"}
)
