/-- AoPS omni_math Problem (id=3188, source=putnam, difficulty=9.0 )
    Informal statement: The 30 edges of a regular icosahedron are distinguished by labeling them $1,2,\dots,30$. How many different ways are there to paint each edge red, white, or blue such that each of the 20 triangular faces of the icosahedron has two edges of the same color and a third edge of a different color?
    Answer: 61917364224
    Solution: The number of such colorings is $2^{20} 3^{10} = 61917364224$. Identify the three colors red, white, and blue with (in some order) the elements of the field \mathbb{F}_3 of three elements (i.e., the ring of integers mod 3). The set of colorings may then be identified with the \mathbb{F}_3-vector space \mathbb{F}_3^E generated by the set $E$ of edges. Let $F$ be the set of faces, and let \mathbb{F}_3^F$ be the \mathbb{F}_3-vector space on the basis $F$; we may then define a linear transformation 
-/
