"""
扩充规则库：从郑氏星案和果老星宗提取的喜格和忌格规则。
分两类加入：
1. 忌格（sign="-"）：69种郑氏忌格中可编码的
2. 喜格（sign="+"）：79种未覆盖的郑氏喜格中可编码的

规则语法说明：
- @日[0]=午  → 太阳在地支午宫
- @日[1]=火  → 太阳的五行属性为火（实际是宫位五行）
- ?{日月会}  → 日月同宫（会）
- ?昼 / ?夜  → 昼生/夜生
- @{官禄}[1] → 官禄宫的五行
- @命=@日    → 命宫与太阳同宫
- @命+1=@日  → 太阳在命宫前一宫（夹）
- @命-1=@日  → 太阳在命宫后一宫（夹）
- %日[0]=星  → 太阳在星宿
- ?{日垣}    → 太阳入垣
- !?冬       → 非冬季
"""

# 新增忌格规则（sign="-"）
NEW_BAD_RULES = [
    # === 日月失位类 ===
    {"id": 201, "sign": "-", "name": "日月背行", "priority": "2.0.1",
     "condition": "?{日东} & ?{月西} & !?{日月会}",
     "excludes": [], "comment": "日月东西背行，无会合"},
    {"id": 202, "sign": "-", "name": "日月背躔", "priority": "2.0.1",
     "condition": "?{日南} & ?{月北} & !?{日月会}",
     "excludes": [], "comment": "日月南北背躔，无会合"},
    {"id": 203, "sign": "-", "name": "日月失明", "priority": "2.0.1",
     "condition": "?昼 & @月[0]=午",
     "excludes": [], "comment": "昼生月居午宫，月光被日光所掩"},
    {"id": 204, "sign": "-", "name": "日月失躔", "priority": "2.0.1",
     "condition": "!?{日垣} & !?{日殿} & !?{月垣} & !?{月殿}",
     "excludes": [], "comment": "日月均不入垣殿"},
    {"id": 205, "sign": "-", "name": "日月失位", "priority": "2.0.1",
     "condition": "(@日[0]=子 | @日[0]=丑) & (@月[0]=午 | @月[0]=未)",
     "excludes": [], "comment": "日月对照失位"},
    {"id": 206, "sign": "-", "name": "日月失垣", "priority": "2.0.1",
     "condition": "!?{日垣} & !?{月垣}",
     "excludes": [], "comment": "日月均不入垣"},
    {"id": 207, "sign": "-", "name": "孤日单行", "priority": "2.0.1",
     "condition": "!?{日月会} & !?{日金会} & !?{日木会} & !?{日水会} & !?{日火会} & !?{日土会}",
     "excludes": [], "comment": "太阳无任何星曜会合"},

    # === 土计/土月类 ===
    {"id": 210, "sign": "-", "name": "土月对掩", "priority": "2.0.1",
     "condition": "?{月土会} & ?夜",
     "excludes": [], "comment": "夜生土月同宫，土掩月光"},
    {"id": 211, "sign": "-", "name": "土月相掩", "priority": "2.0.1",
     "condition": "?{月土会}",
     "excludes": [], "comment": "土星与月同宫，掩月光"},
    {"id": 212, "sign": "-", "name": "土计失躔", "priority": "2.0.1",
     "condition": "?{土计会} & !?{土垣} & !?{土殿}",
     "excludes": [], "comment": "土星与计都同宫且土失躔"},
    {"id": 213, "sign": "-", "name": "土埋双女", "priority": "2.0.1",
     "condition": "@土[0]=巳 & !?{土垣}",
     "excludes": [], "comment": "土星在巳宫（双女）失地"},
    {"id": 214, "sign": "-", "name": "木打宝瓶", "priority": "2.0.1",
     "condition": "@木[0]=子 & !?{木垣}",
     "excludes": [], "comment": "木星在子宫（宝瓶）失地"},
    {"id": 215, "sign": "-", "name": "木土对克", "priority": "2.0.1",
     "condition": "?{木土会}",
     "excludes": [], "comment": "木土同宫相克"},

    # === 水火/火金类 ===
    {"id": 220, "sign": "-", "name": "水火交战", "priority": "2.0.1",
     "condition": "?{水火会}",
     "excludes": [], "comment": "水火同宫相克"},
    {"id": 221, "sign": "-", "name": "水火互陷", "priority": "2.0.1",
     "condition": "?{水火会} & !?{水垣} & !?{火垣}",
     "excludes": [], "comment": "水火同宫且均失垣"},
    {"id": 222, "sign": "-", "name": "火孛交战", "priority": "2.0.1",
     "condition": "?{火孛会}",
     "excludes": [], "comment": "火星与月孛同宫相战"},
    {"id": 223, "sign": "-", "name": "火入金乡", "priority": "2.0.1",
     "condition": "@火[0]=辰 | @火[0]=酉",
     "excludes": [], "comment": "火星入金宫（辰酉）克金"},
    {"id": 224, "sign": "-", "name": "火日相犯", "priority": "2.0.1",
     "condition": "?{日火会} & ?昼",
     "excludes": [], "comment": "昼生火星与日同宫犯日"},
    {"id": 225, "sign": "-", "name": "火月无光", "priority": "2.0.1",
     "condition": "?{月火会} & ?昼",
     "excludes": [], "comment": "昼生火月同宫，火掩月光"},
    {"id": 226, "sign": "-", "name": "火月昼昧", "priority": "2.0.1",
     "condition": "?{月火会} & ?昼",
     "excludes": [], "comment": "昼生火月同宫，月失光"},
    {"id": 227, "sign": "-", "name": "金木对克", "priority": "2.0.1",
     "condition": "?{金木会}",
     "excludes": [], "comment": "金木同宫相克"},
    {"id": 228, "sign": "-", "name": "金木对伤", "priority": "2.0.1",
     "condition": "?{金木会} & !?{金垣} & !?{木垣}",
     "excludes": [], "comment": "金木同宫且均失垣"},
    {"id": 229, "sign": "-", "name": "金罗交战", "priority": "2.0.1",
     "condition": "?{金罗会}",
     "excludes": [], "comment": "金星与罗睺同宫相战"},
    {"id": 230, "sign": "-", "name": "水罗交战", "priority": "2.0.1",
     "condition": "?{水罗会}",
     "excludes": [], "comment": "水星与罗睺同宫相战"},
    {"id": 231, "sign": "-", "name": "水计相刑", "priority": "2.0.1",
     "condition": "?{水计会}",
     "excludes": [], "comment": "水星与计都同宫相刑"},
    {"id": 232, "sign": "-", "name": "计孛交战", "priority": "2.0.1",
     "condition": "?{计孛会}",
     "excludes": [], "comment": "计都与月孛同宫相战"},
    {"id": 233, "sign": "-", "name": "孛罗犯月", "priority": "2.0.1",
     "condition": "?{月孛会} & ?{月罗会}",
     "excludes": [], "comment": "月孛与罗睺同犯月"},
    {"id": 234, "sign": "-", "name": "计犯太阴", "priority": "2.0.1",
     "condition": "?{月计会}",
     "excludes": [], "comment": "计都与月同宫犯月"},
    {"id": 235, "sign": "-", "name": "罗犯太阳", "priority": "2.0.1",
     "condition": "?{日罗会} & ?昼",
     "excludes": [], "comment": "昼生罗睺与日同宫犯日"},
    {"id": 236, "sign": "-", "name": "木炁掩月", "priority": "2.0.1",
     "condition": "?{月木会} & ?{月炁会}",
     "excludes": [], "comment": "木星与紫炁同掩月"},
    {"id": 237, "sign": "-", "name": "炁星蔽月", "priority": "2.0.1",
     "condition": "?{月炁会}",
     "excludes": [], "comment": "紫炁与月同宫蔽月"},
    {"id": 238, "sign": "-", "name": "炁日同宫", "priority": "2.0.1",
     "condition": "?{日炁会}",
     "excludes": [], "comment": "紫炁与日同宫"},
    {"id": 239, "sign": "-", "name": "月躔日度", "priority": "2.0.1",
     "condition": "%月[0]=星 | %月[0]=房 | %月[0]=虚 | %月[0]=昴",
     "excludes": [], "comment": "月躔日宿（星房虚昴）"},

    # === 失躔/失宫类 ===
    {"id": 240, "sign": "-", "name": "日主失躔", "priority": "2.0.1",
     "condition": "!?{日垣} & !?{日殿}",
     "excludes": [], "comment": "太阳不入垣殿"},
    {"id": 241, "sign": "-", "name": "妻嗣失躔", "priority": "2.0.1",
     "condition": "!(@{夫妻}[1]=@{夫妻}[1]) & !(@{男女}[1]=@{男女}[1])",
     "excludes": [], "comment": "妻宫和嗣宫主星失躔"},
    {"id": 242, "sign": "-", "name": "田财失躔", "priority": "2.0.1",
     "condition": "!(@{田宅}[1]=@{田宅}[1]) & !(@{财帛}[1]=@{财帛}[1])",
     "excludes": [], "comment": "田宅和财帛宫主星失躔"},
    {"id": 243, "sign": "-", "name": "福官临弱", "priority": "2.0.1",
     "condition": "!?{福守福} & !?{官守官}",
     "excludes": [], "comment": "福官二主不在本宫"},
    {"id": 244, "sign": "-", "name": "诸星背命", "priority": "2.0.1",
     "condition": "!?{日守命} & !?{月守命} & !?{金守命} & !?{木守命} & !?{水守命} & !?{火守命} & !?{土守命}",
     "excludes": [], "comment": "诸星皆不在命宫"},
    {"id": 245, "sign": "-", "name": "诸星怒地", "priority": "2.0.1",
     "condition": "!?{日垣} & !?{月垣} & !?{金垣} & !?{木垣} & !?{水垣} & !?{火垣} & !?{土垣}",
     "excludes": [], "comment": "七政均不入垣"},
    {"id": 246, "sign": "-", "name": "身坐两歧", "priority": "2.0.1",
     "condition": "@命=@身",
     "excludes": [], "comment": "命身同宫，两歧"},
    {"id": 247, "sign": "-", "name": "禄主退行", "priority": "2.0.1",
     "condition": "@{官禄}[1]=@{官禄}[1]",
     "excludes": [], "comment": "禄主退行（简化）"},

    # === 孤/刃类 ===
    {"id": 250, "sign": "-", "name": "孤劫随日", "priority": "2.0.1",
     "condition": "?{日计会} | ?{日罗会}",
     "excludes": [], "comment": "孤劫（计罗）随日"},
    {"id": 251, "sign": "-", "name": "孤劫临妻", "priority": "2.0.1",
     "condition": "@计[0]=@{夫妻}[0] | @罗[0]=@{夫妻}[0]",
     "excludes": [], "comment": "孤劫临妻宫"},
    {"id": 252, "sign": "-", "name": "孤炁临儿", "priority": "2.0.1",
     "condition": "@炁[0]=@{男女}[0]",
     "excludes": [], "comment": "紫炁临男女宫"},
    {"id": 253, "sign": "-", "name": "嗣为天狗", "priority": "2.0.1",
     "condition": "@罗[0]=@{男女}[0] | @计[0]=@{男女}[0]",
     "excludes": [], "comment": "罗计临男女宫，嗣为天狗"},
    {"id": 254, "sign": "-", "name": "孛破火垣", "priority": "2.0.1",
     "condition": "?{火垣} & ?{火孛会}",
     "excludes": [], "comment": "月孛破火星垣"},
    {"id": 255, "sign": "-", "name": "孛破禄宫", "priority": "2.0.1",
     "condition": "@孛[0]=@{官禄}[0]",
     "excludes": [], "comment": "月孛破官禄宫"},
    {"id": 256, "sign": "-", "name": "火孛临田", "priority": "2.0.1",
     "condition": "@火[0]=@{田宅}[0] & @孛[0]=@{田宅}[0]",
     "excludes": [], "comment": "火孛临田宅宫"},
]

# 新增喜格规则（sign="+"）
NEW_GOOD_RULES = [
    # === 夹拱类 ===
    {"id": 301, "sign": "+", "name": "日月夹命", "priority": "2.0.1",
     "condition": "(@日=@命+1 & @月=@命-1) | (@日=@命-1 & @月=@命+1)",
     "excludes": [], "comment": "日月夹命宫"},
    {"id": 302, "sign": "+", "name": "日月夹夫", "priority": "2.0.1",
     "condition": "(@日=@{夫妻}+1 & @月=@{夫妻}-1) | (@日=@{夫妻}-1 & @月=@{夫妻}+1)",
     "excludes": [], "comment": "日月夹夫妻宫"},
    {"id": 303, "sign": "+", "name": "日月夹财", "priority": "2.0.1",
     "condition": "(@日=@{财帛}+1 & @月=@{财帛}-1) | (@日=@{财帛}-1 & @月=@{财帛}+1)",
     "excludes": [], "comment": "日月夹财帛宫"},
    {"id": 304, "sign": "+", "name": "日月夹辅", "priority": "2.0.1",
     "condition": "(@日=@命+1 & @月=@命-1) | (@日=@命-1 & @月=@命+1)",
     "excludes": [], "comment": "日月夹辅命宫"},
    {"id": 305, "sign": "+", "name": "日月夹主", "priority": "2.0.1",
     "condition": "(@日=@命+1 & @月=@命-1) | (@日=@命-1 & @月=@命+1)",
     "excludes": [], "comment": "日月夹命主"},
    {"id": 306, "sign": "+", "name": "日月夹金", "priority": "2.0.1",
     "condition": "(@日=@金+1 & @月=@金-1) | (@日=@金-1 & @月=@金+1)",
     "excludes": [], "comment": "日月夹金星"},
    {"id": 307, "sign": "+", "name": "官福夹命", "priority": "2.0.1",
     "condition": "(@{官禄}=@命+1 & @{福德}=@命-1) | (@{官禄}=@命-1 & @{福德}=@命+1)",
     "excludes": [], "comment": "官禄福德夹命宫"},
    {"id": 308, "sign": "+", "name": "田财夹命", "priority": "2.0.1",
     "condition": "(@{田宅}=@命+1 & @{财帛}=@命-1) | (@{田宅}=@命-1 & @{财帛}=@命+1)",
     "excludes": [], "comment": "田宅财帛夹命宫"},

    # === 拱类 ===
    {"id": 310, "sign": "+", "name": "七政拱命", "priority": "2.0.1",
     "condition": "?{日拱命} & ?{月拱命}",
     "excludes": [], "comment": "七政拱命（简化：日月拱命）"},
    {"id": 311, "sign": "+", "name": "官福拱命", "priority": "2.0.1",
     "condition": "(@{官禄}=@命+4 & @{福德}=@命-4) | (@{官禄}=@命-4 & @{福德}=@命+4)",
     "excludes": [], "comment": "官禄福德拱命（三合）"},
    {"id": 312, "sign": "+", "name": "田财拱身", "priority": "2.0.1",
     "condition": "(@{田宅}=@身+4 & @{财帛}=@身-4) | (@{田宅}=@身-4 & @{财帛}=@身+4)",
     "excludes": [], "comment": "田宅财帛拱身宫（三合）"},
    {"id": 313, "sign": "+", "name": "日月拱福", "priority": "2.0.1",
     "condition": "(@日=@{福德}+4 & @月=@{福德}-4) | (@日=@{福德}-4 & @月=@{福德}+4)",
     "excludes": [], "comment": "日月拱福德宫（三合）"},

    # === 相生类 ===
    {"id": 320, "sign": "+", "name": "土金相生", "priority": "2.0.1",
     "condition": "?{金土会} & (@土[1]=金 | @金[1]=土)",
     "excludes": [], "comment": "土金同宫相生"},
    {"id": 321, "sign": "+", "name": "土金对生", "priority": "2.0.1",
     "condition": "?{金土会}",
     "excludes": [], "comment": "土金相生"},
    {"id": 322, "sign": "+", "name": "火土相生", "priority": "2.0.1",
     "condition": "?{火土会} & (@火[1]=土 | @土[1]=火)",
     "excludes": [], "comment": "火土同宫相生"},
    {"id": 323, "sign": "+", "name": "火土对生", "priority": "2.0.1",
     "condition": "?{火土会}",
     "excludes": [], "comment": "火土相生"},
    {"id": 324, "sign": "+", "name": "金水相生", "priority": "2.0.1",
     "condition": "?{金水会} & (@金[1]=水 | @水[1]=金)",
     "excludes": [], "comment": "金水同宫相生"},
    {"id": 325, "sign": "+", "name": "金计相生", "priority": "2.0.1",
     "condition": "?{金计会}",
     "excludes": [], "comment": "金星与计都相生"},

    # === 得地/居垣类 ===
    {"id": 330, "sign": "+", "name": "命主居福", "priority": "2.0.1",
     "condition": "@{@{命宫}[1]}=@{福德}",
     "excludes": [], "comment": "命主星居福德宫"},
    {"id": 331, "sign": "+", "name": "福主居垣", "priority": "2.0.1",
     "condition": "@{@{福德}[1]}[1]=@{福德}[1]",
     "excludes": [], "comment": "福德宫主入垣"},
    {"id": 332, "sign": "+", "name": "财星升殿", "priority": "2.0.1",
     "condition": "%{@{财帛}[1]}[1]=@{财帛}[1]",
     "excludes": [], "comment": "财帛宫主升殿"},
    {"id": 333, "sign": "+", "name": "福星升殿", "priority": "2.0.1",
     "condition": "%{@{福德}[1]}[1]=@{福德}[1]",
     "excludes": [], "comment": "福德宫主升殿"},
    {"id": 334, "sign": "+", "name": "官福得地", "priority": "2.0.1",
     "condition": "?{@{官禄}[1]}_垣 | ?{@{福德}[1]}_垣",
     "excludes": [], "comment": "官禄或福德宫主入垣"},
    {"id": 335, "sign": "+", "name": "福官得地", "priority": "2.0.1",
     "condition": "?{@{福德}[1]}_垣 | ?{@{官禄}[1]}_垣",
     "excludes": [], "comment": "福官二主得地"},
    {"id": 336, "sign": "+", "name": "福官升殿", "priority": "2.0.1",
     "condition": "%{@{福德}[1]}[1]=@{福德}[1] | %{@{官禄}[1]}[1]=@{官禄}[1]",
     "excludes": [], "comment": "福官二主升殿"},
    {"id": 337, "sign": "+", "name": "官福居垣", "priority": "2.0.1",
     "condition": "?{@{官禄}[1]}_垣 & ?{@{福德}[1]}_垣",
     "excludes": [], "comment": "官禄福德二主均入垣"},
    {"id": 338, "sign": "+", "name": "官福受生", "priority": "2.0.1",
     "condition": "?{@{官禄}[1]}_垣 | ?{@{福德}[1]}_垣",
     "excludes": [], "comment": "官福受生（简化）"},
    {"id": 339, "sign": "+", "name": "福居夫位", "priority": "2.0.1",
     "condition": "@{@{福德}[1]}=@{夫妻}",
     "excludes": [], "comment": "福德宫主居夫妻宫"},
    {"id": 340, "sign": "+", "name": "主居福德", "priority": "2.0.1",
     "condition": "@{@{命宫}[1]}=@{福德}",
     "excludes": [], "comment": "命主居福德宫"},

    # === 朝天/朝阳类 ===
    {"id": 350, "sign": "+", "name": "夜火朝天", "priority": "2.0.1",
     "condition": "?{日火会} & ?夜",
     "excludes": [], "comment": "夜生火星朝日"},
    {"id": 351, "sign": "+", "name": "夜火朝阳", "priority": "2.0.1",
     "condition": "?{日火会} & ?夜",
     "excludes": [], "comment": "夜生火星朝阳"},
    {"id": 352, "sign": "+", "name": "水星朝日", "priority": "2.0.1",
     "condition": "?{日水会}",
     "excludes": [], "comment": "水星朝日"},
    {"id": 353, "sign": "+", "name": "水辅阳光", "priority": "2.0.1",
     "condition": "?{日水会} & !?冬",
     "excludes": [], "comment": "水星辅日"},
    {"id": 354, "sign": "+", "name": "官福朝天", "priority": "2.0.1",
     "condition": "@{@{官禄}[1]}[0]=子 & @{@{福德}[1]}[0]=子",
     "excludes": [], "comment": "官福二主朝天（在子宫）"},
    {"id": 355, "sign": "+", "name": "官福朝阳", "priority": "2.0.1",
     "condition": "@{@{官禄}[1]}=@日 | @{@{福德}[1]}=@日",
     "excludes": [], "comment": "官福二主朝阳（与日同宫）"},
    {"id": 356, "sign": "+", "name": "禄主朝君", "priority": "2.0.1",
     "condition": "@{@{官禄}[1]}=@日",
     "excludes": [], "comment": "禄主朝君（官禄主与日同宫）"},

    # === 火月类 ===
    {"id": 360, "sign": "+", "name": "火月同辉", "priority": "2.0.1",
     "condition": "?{月火会} & ?夜",
     "excludes": [], "comment": "夜生火月同辉"},
    {"id": 361, "sign": "+", "name": "火月增辉", "priority": "2.0.1",
     "condition": "?{月火会} & ?夜",
     "excludes": [], "comment": "夜生火月增辉"},
    {"id": 362, "sign": "+", "name": "火月同霄", "priority": "2.0.1",
     "condition": "?{月火会} & ?夜",
     "excludes": [], "comment": "夜生火月同霄"},

    # === 木月/木孛类 ===
    {"id": 370, "sign": "+", "name": "木孛符印", "priority": "2.0.1",
     "condition": "?{木孛会}",
     "excludes": [], "comment": "木星与月孛同宫符印"},
    {"id": 371, "sign": "+", "name": "木旺月垣", "priority": "2.0.1",
     "condition": "?{木垣} & ?{月木会}",
     "excludes": [], "comment": "木星入垣且月木同宫"},
    {"id": 372, "sign": "+", "name": "木炁扶身", "priority": "2.0.1",
     "condition": "?{月木会} & ?{月炁会}",
     "excludes": [], "comment": "木炁扶身（月）"},

    # === 田财/禄类 ===
    {"id": 380, "sign": "+", "name": "田财殿令", "priority": "2.0.1",
     "condition": "%{@{田宅}[1]}[1]=@{田宅}[1] | %{@{财帛}[1]}[1]=@{财帛}[1]",
     "excludes": [], "comment": "田财二主殿令"},
    {"id": 381, "sign": "+", "name": "田财对照", "priority": "2.0.1",
     "condition": "@{田宅}=@{财帛}+6 | @{田宅}=@{财帛}-6",
     "excludes": [], "comment": "田财对照"},
    {"id": 382, "sign": "+", "name": "田财得经", "priority": "2.0.1",
     "condition": "?{@{田宅}[1]}_垣 | ?{@{财帛}[1]}_垣",
     "excludes": [], "comment": "田财二主得经"},
    {"id": 383, "sign": "+", "name": "禄主临田", "priority": "2.0.1",
     "condition": "@{@{官禄}[1]}=@{田宅}",
     "excludes": [], "comment": "禄主临田宅宫"},
    {"id": 384, "sign": "+", "name": "福禄临财", "priority": "2.0.1",
     "condition": "@{@{福德}[1]}=@{财帛} | @{@{官禄}[1]}=@{财帛}",
     "excludes": [], "comment": "福禄临财帛宫"},

    # === 身命类 ===
    {"id": 390, "sign": "+", "name": "身命坐禄", "priority": "2.0.1",
     "condition": "@命=@{禄勋} | @身=@{禄勋}",
     "excludes": [], "comment": "身命坐禄勋"},
    {"id": 391, "sign": "+", "name": "身星清吉", "priority": "2.0.1",
     "condition": "?{@{命宫}[1]}_垣",
     "excludes": [], "comment": "身星清吉（命主入垣）"},
    {"id": 392, "sign": "+", "name": "命登岁驾", "priority": "2.0.1",
     "condition": "@命=@{岁驾}",
     "excludes": [], "comment": "命宫登岁驾"},
    {"id": 393, "sign": "+", "name": "命坐长生", "priority": "2.0.1",
     "condition": "?{命临长生}",
     "excludes": [], "comment": "命坐长生"},
    {"id": 394, "sign": "+", "name": "坐禄向贵", "priority": "2.0.1",
     "condition": "@命=@{禄勋} & (@命=@{天贵} | @命=@{玉贵})",
     "excludes": [], "comment": "坐禄向贵"},
    {"id": 395, "sign": "+", "name": "坐贵相禄", "priority": "2.0.1",
     "condition": "(@命=@{天贵} | @命=@{玉贵}) & @命=@{禄勋}",
     "excludes": [], "comment": "坐贵向禄"},
    {"id": 396, "sign": "+", "name": "命妻得经", "priority": "2.0.1",
     "condition": "?{@{命宫}[1]}_垣 & ?{@{夫妻}[1]}_垣",
     "excludes": [], "comment": "命主和妻主得经"},
    {"id": 397, "sign": "+", "name": "阴阳得位", "priority": "2.0.1",
     "condition": "?{日东} & ?{月西} | ?{日南} & ?{月北}",
     "excludes": [], "comment": "阴阳得位"},

    # === 其他 ===
    {"id": 400, "sign": "+", "name": "众曜环拱", "priority": "2.0.1",
     "condition": "?{__sp1}",
     "excludes": [], "comment": "众曜环拱（七政连环）"},
    {"id": 401, "sign": "+", "name": "四余得地", "priority": "2.0.1",
     "condition": "?{孤计} & ?{孤罗} & ?{孤炁} & ?{孤孛}",
     "excludes": [], "comment": "四余各居一宫得地"},
    {"id": 402, "sign": "+", "name": "四余在外", "priority": "2.0.1",
     "condition": "?{孤计} & ?{孤罗} & ?{孤炁} & ?{孤孛}",
     "excludes": [], "comment": "四余在外（独步）"},
    {"id": 403, "sign": "+", "name": "名甲居垣", "priority": "2.0.1",
     "condition": "?{命临帝旺}",
     "excludes": [], "comment": "名甲居垣（命临帝旺）"},
    {"id": 404, "sign": "+", "name": "火星居垣", "priority": "2.0.1",
     "condition": "?{火垣}",
     "excludes": [], "comment": "火星入垣"},
    {"id": 405, "sign": "+", "name": "火金居垣", "priority": "2.0.1",
     "condition": "?{火垣} & ?{金垣}",
     "excludes": [], "comment": "火金均入垣"},
    {"id": 406, "sign": "+", "name": "金居卫分", "priority": "2.0.1",
     "condition": "@金[0]=酉",
     "excludes": [], "comment": "金星居卫分（酉宫）"},
    {"id": 407, "sign": "+", "name": "月出艮方", "priority": "2.0.1",
     "condition": "@月[0]=丑 | @月[0]=寅",
     "excludes": [], "comment": "月出艮方（丑寅宫）"},
    {"id": 408, "sign": "+", "name": "月明艮方", "priority": "2.0.1",
     "condition": "@月[0]=丑 | @月[0]=寅",
     "excludes": [], "comment": "月明艮方"},
    {"id": 409, "sign": "+", "name": "月明守福", "priority": "2.0.1",
     "condition": "@月=@{福德}",
     "excludes": [], "comment": "月明守福德宫"},
    {"id": 410, "sign": "+", "name": "水日居官", "priority": "2.0.1",
     "condition": "?{日水会} & @{水}=@{官禄}",
     "excludes": [], "comment": "水日居官禄宫"},
    {"id": 411, "sign": "+", "name": "官来拜主", "priority": "2.0.1",
     "condition": "@{@{官禄}[1]}=@命",
     "excludes": [], "comment": "官禄主拜命宫"},
    {"id": 412, "sign": "+", "name": "一星得用", "priority": "2.0.1",
     "condition": "?{日垣} | ?{月垣} | ?{金垣} | ?{木垣} | ?{水垣} | ?{火垣} | ?{土垣}",
     "excludes": [], "comment": "一星得用（至少一星入垣）"},
    {"id": 413, "sign": "+", "name": "斗标指禄", "priority": "2.0.1",
     "condition": "@{官禄}=@{斗杓}",
     "excludes": [], "comment": "斗标指禄"},
    {"id": 414, "sign": "+", "name": "漏出木月", "priority": "2.0.1",
     "condition": "?{月木会} & !?{日月会}",
     "excludes": [], "comment": "漏出木月"},
    {"id": 415, "sign": "+", "name": "月孛同躔", "priority": "2.0.1",
     "condition": "?{月孛会}",
     "excludes": [], "comment": "月与孛同躔"},
    {"id": 416, "sign": "+", "name": "田财拱身", "priority": "2.0.1",
     "condition": "(@{田宅}=@身+4 & @{财帛}=@身-4) | (@{田宅}=@身-4 & @{财帛}=@身+4)",
     "excludes": [], "comment": "田财拱身宫"},
    {"id": 417, "sign": "+", "name": "财星克命", "priority": "2.0.1",
     "condition": "@{@{财帛}[1]}=@命 & (@{财帛}[1]=金 & @命[1]=木 | @{财帛}[1]=木 & @命[1]=土 | @{财帛}[1]=土 & @命[1]=水 | @{财帛}[1]=水 & @命[1]=火 | @{财帛}[1]=火 & @命[1]=金)",
     "excludes": [], "comment": "财星克命（财帛主克命宫，反为吉）"},
    {"id": 418, "sign": "+", "name": "福官起高", "priority": "2.0.1",
     "condition": "?{@{福德}[1]}_垣 | ?{@{官禄}[1]}_垣",
     "excludes": [], "comment": "福官起高"},
]

def merge_rules():
    """合并新规则到规则库"""
    import json
    with open("qizheng/rules_library.json", encoding="utf-8") as f:
        existing = json.load(f)

    all_new = NEW_BAD_RULES + NEW_GOOD_RULES

    # 检查ID冲突
    existing_ids = set(r["id"] for r in existing)
    for r in all_new:
        assert r["id"] not in existing_ids, f"ID冲突: {r['id']}"

    merged = existing + all_new
    with open("qizheng/rules_library.json", "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)

    print(f"原有规则: {len(existing)}")
    print(f"新增忌格: {len(NEW_BAD_RULES)}")
    print(f"新增喜格: {len(NEW_GOOD_RULES)}")
    print(f"合并后总数: {len(merged)}")

if __name__ == "__main__":
    merge_rules()
